// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attempts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStreak = `-- name: GetStreak :one
SELECT user_id, current_len, longest_len, last_day FROM streaks WHERE user_id = $1
`

func (q *Queries) GetStreak(ctx context.Context, userID int64) (Streak, error) {
	row := q.db.QueryRow(ctx, getStreak, userID)
	var i Streak
	err := row.Scan(
		&i.UserID,
		&i.CurrentLen,
		&i.LongestLen,
		&i.LastDay,
	)
	return i, err
}

const insertAttempt = `-- name: InsertAttempt :one
INSERT INTO attempts (user_id, course_item_id, mode, client_grade, server_grade)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, course_item_id, mode, client_grade, server_grade, created_at
`

type InsertAttemptParams struct {
	UserID       int64  `json:"user_id"`
	CourseItemID int64  `json:"course_item_id"`
	Mode         string `json:"mode"`
	ClientGrade  string `json:"client_grade"`
	ServerGrade  string `json:"server_grade"`
}

func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, insertAttempt,
		arg.UserID,
		arg.CourseItemID,
		arg.Mode,
		arg.ClientGrade,
		arg.ServerGrade,
	)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseItemID,
		&i.Mode,
		&i.ClientGrade,
		&i.ServerGrade,
		&i.CreatedAt,
	)
	return i, err
}

const listCourseProgress = `-- name: ListCourseProgress :many
SELECT ci.course_id AS course_id,
       COUNT(*) FILTER (WHERE p.cleared) AS cleared,
       COUNT(*)                          AS total
FROM course_items ci
LEFT JOIN progress p
  ON p.course_item_id = ci.id AND p.user_id = $1
GROUP BY ci.course_id
`

type ListCourseProgressRow struct {
	CourseID int64 `json:"course_id"`
	Cleared  int64 `json:"cleared"`
	Total    int64 `json:"total"`
}

func (q *Queries) ListCourseProgress(ctx context.Context, userID int64) ([]ListCourseProgressRow, error) {
	rows, err := q.db.Query(ctx, listCourseProgress, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCourseProgressRow
	for rows.Next() {
		var i ListCourseProgressRow
		if err := rows.Scan(&i.CourseID, &i.Cleared, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProgress = `-- name: ListUserProgress :many
SELECT p.course_item_id, p.grade, p.cleared, bv.book, bv.chapter, bv.verse
FROM progress p
JOIN course_items ci ON ci.id = p.course_item_id
JOIN bible_verses bv ON bv.id = ci.verse_id
WHERE p.user_id = $1
`

type ListUserProgressRow struct {
	CourseItemID int64  `json:"course_item_id"`
	Grade        string `json:"grade"`
	Cleared      bool   `json:"cleared"`
	Book         int16  `json:"book"`
	Chapter      int16  `json:"chapter"`
	Verse        int16  `json:"verse"`
}

func (q *Queries) ListUserProgress(ctx context.Context, userID int64) ([]ListUserProgressRow, error) {
	rows, err := q.db.Query(ctx, listUserProgress, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserProgressRow
	for rows.Next() {
		var i ListUserProgressRow
		if err := rows.Scan(
			&i.CourseItemID,
			&i.Grade,
			&i.Cleared,
			&i.Book,
			&i.Chapter,
			&i.Verse,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProgress = `-- name: UpsertProgress :exec
INSERT INTO progress (user_id, course_item_id, grade, cleared, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (user_id, course_item_id)
DO UPDATE SET grade = EXCLUDED.grade, cleared = EXCLUDED.cleared, updated_at = now()
`

type UpsertProgressParams struct {
	UserID       int64  `json:"user_id"`
	CourseItemID int64  `json:"course_item_id"`
	Grade        string `json:"grade"`
	Cleared      bool   `json:"cleared"`
}

func (q *Queries) UpsertProgress(ctx context.Context, arg UpsertProgressParams) error {
	_, err := q.db.Exec(ctx, upsertProgress,
		arg.UserID,
		arg.CourseItemID,
		arg.Grade,
		arg.Cleared,
	)
	return err
}

const upsertStreak = `-- name: UpsertStreak :exec
INSERT INTO streaks (user_id, current_len, longest_len, last_day)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id)
DO UPDATE SET current_len = EXCLUDED.current_len, longest_len = EXCLUDED.longest_len, last_day = EXCLUDED.last_day
`

type UpsertStreakParams struct {
	UserID     int64       `json:"user_id"`
	CurrentLen int32       `json:"current_len"`
	LongestLen int32       `json:"longest_len"`
	LastDay    pgtype.Date `json:"last_day"`
}

func (q *Queries) UpsertStreak(ctx context.Context, arg UpsertStreakParams) error {
	_, err := q.db.Exec(ctx, upsertStreak,
		arg.UserID,
		arg.CurrentLen,
		arg.LongestLen,
		arg.LastDay,
	)
	return err
}
