// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_codes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentAuthCodes = `-- name: CountRecentAuthCodes :one
SELECT count(*) FROM auth_codes
WHERE user_id = $1 AND purpose = $2 AND created_at > now() - interval '1 hour'
`

type CountRecentAuthCodesParams struct {
	UserID  int64  `json:"user_id"`
	Purpose string `json:"purpose"`
}

func (q *Queries) CountRecentAuthCodes(ctx context.Context, arg CountRecentAuthCodesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentAuthCodes, arg.UserID, arg.Purpose)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthCode = `-- name: CreateAuthCode :one
INSERT INTO auth_codes (user_id, purpose, code_hash, email, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, purpose, code_hash, email, attempts, expires_at, created_at
`

type CreateAuthCodeParams struct {
	UserID    int64              `json:"user_id"`
	Purpose   string             `json:"purpose"`
	CodeHash  string             `json:"code_hash"`
	Email     string             `json:"email"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAuthCode(ctx context.Context, arg CreateAuthCodeParams) (AuthCode, error) {
	row := q.db.QueryRow(ctx, createAuthCode,
		arg.UserID,
		arg.Purpose,
		arg.CodeHash,
		arg.Email,
		arg.ExpiresAt,
	)
	var i AuthCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.CodeHash,
		&i.Email,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAuthCodes = `-- name: DeleteAuthCodes :exec
DELETE FROM auth_codes WHERE user_id = $1 AND purpose = $2
`

type DeleteAuthCodesParams struct {
	UserID  int64  `json:"user_id"`
	Purpose string `json:"purpose"`
}

func (q *Queries) DeleteAuthCodes(ctx context.Context, arg DeleteAuthCodesParams) error {
	_, err := q.db.Exec(ctx, deleteAuthCodes, arg.UserID, arg.Purpose)
	return err
}

const getLatestAuthCode = `-- name: GetLatestAuthCode :one
SELECT id, user_id, purpose, code_hash, email, attempts, expires_at, created_at FROM auth_codes
WHERE user_id = $1 AND purpose = $2 AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestAuthCodeParams struct {
	UserID  int64  `json:"user_id"`
	Purpose string `json:"purpose"`
}

func (q *Queries) GetLatestAuthCode(ctx context.Context, arg GetLatestAuthCodeParams) (AuthCode, error) {
	row := q.db.QueryRow(ctx, getLatestAuthCode, arg.UserID, arg.Purpose)
	var i AuthCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.CodeHash,
		&i.Email,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementAuthCodeAttempts = `-- name: IncrementAuthCodeAttempts :exec
UPDATE auth_codes SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementAuthCodeAttempts(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementAuthCodeAttempts, id)
	return err
}
