// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCourseBySlug = `-- name: GetCourseBySlug :one
SELECT id, slug, title, theme, ord, hidden FROM courses WHERE slug = $1
`

func (q *Queries) GetCourseBySlug(ctx context.Context, slug string) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseBySlug, slug)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Theme,
		&i.Ord,
		&i.Hidden,
	)
	return i, err
}

const getCourseItemVerse = `-- name: GetCourseItemVerse :one
SELECT
  ci.id AS course_item_id,
  bv.book,
  bv.chapter,
  bv.verse,
  bv.text
FROM course_items ci
JOIN bible_verses bv ON bv.id = ci.verse_id
WHERE ci.id = $1
`

type GetCourseItemVerseRow struct {
	CourseItemID int64  `json:"course_item_id"`
	Book         int16  `json:"book"`
	Chapter      int16  `json:"chapter"`
	Verse        int16  `json:"verse"`
	Text         string `json:"text"`
}

// 시도 제출 시 정답 텍스트 확보(채점 분모): course_item_id → 절 텍스트
func (q *Queries) GetCourseItemVerse(ctx context.Context, id int64) (GetCourseItemVerseRow, error) {
	row := q.db.QueryRow(ctx, getCourseItemVerse, id)
	var i GetCourseItemVerseRow
	err := row.Scan(
		&i.CourseItemID,
		&i.Book,
		&i.Chapter,
		&i.Verse,
		&i.Text,
	)
	return i, err
}

const getSectionByID = `-- name: GetSectionByID :one
SELECT id, course_id, title, ord FROM course_sections WHERE id = $1
`

func (q *Queries) GetSectionByID(ctx context.Context, id int64) (CourseSection, error) {
	row := q.db.QueryRow(ctx, getSectionByID, id)
	var i CourseSection
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Ord,
	)
	return i, err
}

const listCourseItems = `-- name: ListCourseItems :many
SELECT id, course_id, verse_id, ord, topic, section_id FROM course_items WHERE course_id = $1 ORDER BY ord
`

func (q *Queries) ListCourseItems(ctx context.Context, courseID int64) ([]CourseItem, error) {
	rows, err := q.db.Query(ctx, listCourseItems, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseItem
	for rows.Next() {
		var i CourseItem
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.VerseID,
			&i.Ord,
			&i.Topic,
			&i.SectionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseItemsWithVerse = `-- name: ListCourseItemsWithVerse :many
SELECT
  ci.id        AS course_item_id,
  ci.ord,
  ci.topic,
  bv.book,
  bv.chapter,
  bv.verse,
  bv.text
FROM course_items ci
JOIN bible_verses bv ON bv.id = ci.verse_id
WHERE ci.course_id = $1
ORDER BY ci.ord
`

type ListCourseItemsWithVerseRow struct {
	CourseItemID int64       `json:"course_item_id"`
	Ord          int32       `json:"ord"`
	Topic        pgtype.Text `json:"topic"`
	Book         int16       `json:"book"`
	Chapter      int16       `json:"chapter"`
	Verse        int16       `json:"verse"`
	Text         string      `json:"text"`
}

// 코스 상세 화면: 코스아이템 목록 + 각 절 텍스트를 한 번에 조회
func (q *Queries) ListCourseItemsWithVerse(ctx context.Context, courseID int64) ([]ListCourseItemsWithVerseRow, error) {
	rows, err := q.db.Query(ctx, listCourseItemsWithVerse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCourseItemsWithVerseRow
	for rows.Next() {
		var i ListCourseItemsWithVerseRow
		if err := rows.Scan(
			&i.CourseItemID,
			&i.Ord,
			&i.Topic,
			&i.Book,
			&i.Chapter,
			&i.Verse,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourses = `-- name: ListCourses :many
SELECT id, slug, title, theme, ord, hidden FROM courses WHERE NOT hidden ORDER BY ord
`

func (q *Queries) ListCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Theme,
			&i.Ord,
			&i.Hidden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsBySection = `-- name: ListItemsBySection :many
SELECT
  ci.id AS course_item_id,
  ci.ord,
  ci.topic,
  bv.book,
  bv.chapter,
  bv.verse,
  bv.text
FROM course_items ci
JOIN bible_verses bv ON bv.id = ci.verse_id
WHERE ci.section_id = $1
ORDER BY ci.ord
`

type ListItemsBySectionRow struct {
	CourseItemID int64       `json:"course_item_id"`
	Ord          int32       `json:"ord"`
	Topic        pgtype.Text `json:"topic"`
	Book         int16       `json:"book"`
	Chapter      int16       `json:"chapter"`
	Verse        int16       `json:"verse"`
	Text         string      `json:"text"`
}

// 섹션 상세: 섹션 내 절 목록 + 텍스트
func (q *Queries) ListItemsBySection(ctx context.Context, sectionID pgtype.Int8) ([]ListItemsBySectionRow, error) {
	rows, err := q.db.Query(ctx, listItemsBySection, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsBySectionRow
	for rows.Next() {
		var i ListItemsBySectionRow
		if err := rows.Scan(
			&i.CourseItemID,
			&i.Ord,
			&i.Topic,
			&i.Book,
			&i.Chapter,
			&i.Verse,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionsByCourse = `-- name: ListSectionsByCourse :many
SELECT id, course_id, title, ord FROM course_sections WHERE course_id = $1 ORDER BY ord
`

func (q *Queries) ListSectionsByCourse(ctx context.Context, courseID int64) ([]CourseSection, error) {
	rows, err := q.db.Query(ctx, listSectionsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseSection
	for rows.Next() {
		var i CourseSection
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Ord,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
