// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO item_favorites(user_id, course_item_id)
VALUES ($1, $2)
ON CONFLICT (user_id, course_item_id) DO NOTHING
`

type AddFavoriteParams struct {
	UserID       int64 `json:"user_id"`
	CourseItemID int64 `json:"course_item_id"`
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.CourseItemID)
	return err
}

const listFavoriteItems = `-- name: ListFavoriteItems :many
SELECT
  ci.id          AS course_item_id,
  ci.topic,
  co.slug        AS course_slug,
  co.title       AS course_title,
  cs.id          AS section_id,
  cs.title       AS section_title,
  bv.book,
  bv.chapter,
  bv.verse,
  bv.text,
  f.created_at
FROM item_favorites f
JOIN course_items ci ON ci.id = f.course_item_id
JOIN courses co ON co.id = ci.course_id
LEFT JOIN course_sections cs ON cs.id = ci.section_id
JOIN bible_verses bv ON bv.id = ci.verse_id
WHERE f.user_id = $1
ORDER BY f.created_at DESC
`

type ListFavoriteItemsRow struct {
	CourseItemID int64              `json:"course_item_id"`
	Topic        pgtype.Text        `json:"topic"`
	CourseSlug   string             `json:"course_slug"`
	CourseTitle  string             `json:"course_title"`
	SectionID    pgtype.Int8        `json:"section_id"`
	SectionTitle pgtype.Text        `json:"section_title"`
	Book         int16              `json:"book"`
	Chapter      int16              `json:"chapter"`
	Verse        int16              `json:"verse"`
	Text         string             `json:"text"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListFavoriteItems(ctx context.Context, userID int64) ([]ListFavoriteItemsRow, error) {
	rows, err := q.db.Query(ctx, listFavoriteItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFavoriteItemsRow
	for rows.Next() {
		var i ListFavoriteItemsRow
		if err := rows.Scan(
			&i.CourseItemID,
			&i.Topic,
			&i.CourseSlug,
			&i.CourseTitle,
			&i.SectionID,
			&i.SectionTitle,
			&i.Book,
			&i.Chapter,
			&i.Verse,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM item_favorites
WHERE user_id = $1 AND course_item_id = $2
`

type RemoveFavoriteParams struct {
	UserID       int64 `json:"user_id"`
	CourseItemID int64 `json:"course_item_id"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.CourseItemID)
	return err
}
