// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attempt struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	CourseItemID int64              `json:"course_item_id"`
	Mode         string             `json:"mode"`
	ClientGrade  string             `json:"client_grade"`
	ServerGrade  string             `json:"server_grade"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AuthCode struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Purpose   string             `json:"purpose"`
	CodeHash  string             `json:"code_hash"`
	Email     string             `json:"email"`
	Attempts  int32              `json:"attempts"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BibleVerse struct {
	ID      int64  `json:"id"`
	Book    int16  `json:"book"`
	Chapter int16  `json:"chapter"`
	Verse   int16  `json:"verse"`
	Text    string `json:"text"`
}

type Course struct {
	ID           int64       `json:"id"`
	Slug         string      `json:"slug"`
	Title        string      `json:"title"`
	Theme        pgtype.Text `json:"theme"`
	Ord          int32       `json:"ord"`
	Hidden       bool        `json:"hidden"`
	Category     string      `json:"category"`
	TitleEn      pgtype.Text `json:"title_en"`
	Commentary   pgtype.Text `json:"commentary"`
	CommentaryEn pgtype.Text `json:"commentary_en"`
}

type CourseItem struct {
	ID        int64       `json:"id"`
	CourseID  int64       `json:"course_id"`
	VerseID   int64       `json:"verse_id"`
	Ord       int32       `json:"ord"`
	Topic     pgtype.Text `json:"topic"`
	SectionID pgtype.Int8 `json:"section_id"`
	TopicEn   pgtype.Text `json:"topic_en"`
}

type CourseSection struct {
	ID       int64       `json:"id"`
	CourseID int64       `json:"course_id"`
	Title    string      `json:"title"`
	Ord      int32       `json:"ord"`
	TitleEn  pgtype.Text `json:"title_en"`
}

type ItemFavorite struct {
	UserID       int64              `json:"user_id"`
	CourseItemID int64              `json:"course_item_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Progress struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	CourseItemID int64              `json:"course_item_id"`
	Grade        string             `json:"grade"`
	Cleared      bool               `json:"cleared"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Streak struct {
	UserID     int64       `json:"user_id"`
	CurrentLen int32       `json:"current_len"`
	LongestLen int32       `json:"longest_len"`
	LastDay    pgtype.Date `json:"last_day"`
}

type User struct {
	ID                   int64              `json:"id"`
	DisplayName          string             `json:"display_name"`
	PasswordHash         string             `json:"password_hash"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	Username             string             `json:"username"`
	Lives                int32              `json:"lives"`
	LivesUpdatedAt       pgtype.Timestamptz `json:"lives_updated_at"`
	Theme                string             `json:"theme"`
	Language             string             `json:"language"`
	DisplayNameUpdatedAt pgtype.Timestamptz `json:"display_name_updated_at"`
	Email                pgtype.Text        `json:"email"`
	GoogleSub            pgtype.Text        `json:"google_sub"`
	AppleSub             pgtype.Text        `json:"apple_sub"`
	EmailVerifiedAt      pgtype.Timestamptz `json:"email_verified_at"`
}

type VerseSegment struct {
	ID           int64  `json:"id"`
	VerseID      int64  `json:"verse_id"`
	SegmentLabel string `json:"segment_label"`
	Text         string `json:"text"`
	WordCount    int32  `json:"word_count"`
	Ord          int32  `json:"ord"`
}

type WordGlossary struct {
	ID      int64       `json:"id"`
	WordKey string      `json:"word_key"`
	KoGloss string      `json:"ko_gloss"`
	Note    pgtype.Text `json:"note"`
}
