// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resume.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLastAttempt = `-- name: GetLastAttempt :one
SELECT
  ci.id          AS course_item_id,
  ci.ord         AS item_ord,
  co.id          AS course_id,
  co.slug,
  co.title       AS course_title,
  co.title_en    AS course_title_en,
  cs.id          AS section_id,
  cs.title       AS section_title,
  cs.title_en    AS section_title_en,
  bv.book,
  bv.chapter,
  bv.verse,
  a.created_at
FROM attempts a
JOIN course_items ci ON ci.id = a.course_item_id
JOIN courses co ON co.id = ci.course_id AND NOT co.hidden
LEFT JOIN course_sections cs ON cs.id = ci.section_id
JOIN bible_verses bv ON bv.id = ci.verse_id
WHERE a.user_id = $1
ORDER BY a.created_at DESC
LIMIT 1
`

type GetLastAttemptRow struct {
	CourseItemID    int64              `json:"course_item_id"`
	ItemOrd         int32              `json:"item_ord"`
	CourseID        int64              `json:"course_id"`
	Slug            string             `json:"slug"`
	CourseTitle     string             `json:"course_title"`
	CourseTitleEn   pgtype.Text        `json:"course_title_en"`
	SectionID       pgtype.Int8        `json:"section_id"`
	SectionTitle    pgtype.Text        `json:"section_title"`
	SectionTitleEn  pgtype.Text        `json:"section_title_en"`
	Book            int16              `json:"book"`
	Chapter         int16              `json:"chapter"`
	Verse           int16              `json:"verse"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetLastAttempt(ctx context.Context, userID int64) (GetLastAttemptRow, error) {
	row := q.db.QueryRow(ctx, getLastAttempt, userID)
	var i GetLastAttemptRow
	err := row.Scan(
		&i.CourseItemID,
		&i.ItemOrd,
		&i.CourseID,
		&i.Slug,
		&i.CourseTitle,
		&i.CourseTitleEn,
		&i.SectionID,
		&i.SectionTitle,
		&i.SectionTitleEn,
		&i.Book,
		&i.Chapter,
		&i.Verse,
		&i.CreatedAt,
	)
	return i, err
}

const getNextUnclearedItem = `-- name: GetNextUnclearedItem :one
SELECT
  ci.id          AS course_item_id,
  ci.ord,
  cs.id          AS section_id,
  cs.title       AS section_title,
  cs.title_en    AS section_title_en,
  bv.book,
  bv.chapter,
  bv.verse
FROM course_items ci
LEFT JOIN progress p ON p.course_item_id = ci.id AND p.user_id = $1
LEFT JOIN course_sections cs ON cs.id = ci.section_id
JOIN bible_verses bv ON bv.id = ci.verse_id
WHERE ci.course_id = $2
  AND COALESCE(p.cleared, false) = false
ORDER BY (ci.ord < $3), ci.ord
LIMIT 1
`

type GetNextUnclearedItemParams struct {
	UserID   int64 `json:"user_id"`
	CourseID int64 `json:"course_id"`
	Ord      int32 `json:"ord"`
}

type GetNextUnclearedItemRow struct {
	CourseItemID   int64       `json:"course_item_id"`
	Ord            int32       `json:"ord"`
	SectionID      pgtype.Int8 `json:"section_id"`
	SectionTitle   pgtype.Text `json:"section_title"`
	SectionTitleEn pgtype.Text `json:"section_title_en"`
	Book           int16       `json:"book"`
	Chapter        int16       `json:"chapter"`
	Verse          int16       `json:"verse"`
}

func (q *Queries) GetNextUnclearedItem(ctx context.Context, arg GetNextUnclearedItemParams) (GetNextUnclearedItemRow, error) {
	row := q.db.QueryRow(ctx, getNextUnclearedItem, arg.UserID, arg.CourseID, arg.Ord)
	var i GetNextUnclearedItemRow
	err := row.Scan(
		&i.CourseItemID,
		&i.Ord,
		&i.SectionID,
		&i.SectionTitle,
		&i.SectionTitleEn,
		&i.Book,
		&i.Chapter,
		&i.Verse,
	)
	return i, err
}
