// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"
)

const getBookProgress = `-- name: GetBookProgress :many
SELECT bv.book AS book,
       COUNT(DISTINCT bv.id) FILTER (WHERE p.cleared) AS cleared,
       COUNT(DISTINCT bv.id)                          AS total
FROM course_items ci
JOIN bible_verses bv ON bv.id = ci.verse_id
LEFT JOIN progress p ON p.course_item_id = ci.id AND p.user_id = $1
GROUP BY bv.book
ORDER BY bv.book
`

type GetBookProgressRow struct {
	Book    int16 `json:"book"`
	Cleared int64 `json:"cleared"`
	Total   int64 `json:"total"`
}

func (q *Queries) GetBookProgress(ctx context.Context, userID int64) ([]GetBookProgressRow, error) {
	rows, err := q.db.Query(ctx, getBookProgress, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookProgressRow
	for rows.Next() {
		var i GetBookProgressRow
		if err := rows.Scan(&i.Book, &i.Cleared, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryProgress = `-- name: GetCategoryProgress :many
SELECT c.category AS category,
       COUNT(*) FILTER (WHERE p.cleared) AS cleared,
       COUNT(*)                          AS total
FROM course_items ci
JOIN courses c ON c.id = ci.course_id
LEFT JOIN progress p ON p.course_item_id = ci.id AND p.user_id = $1
GROUP BY c.category
`

type GetCategoryProgressRow struct {
	Category string `json:"category"`
	Cleared  int64  `json:"cleared"`
	Total    int64  `json:"total"`
}

func (q *Queries) GetCategoryProgress(ctx context.Context, userID int64) ([]GetCategoryProgressRow, error) {
	rows, err := q.db.Query(ctx, getCategoryProgress, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryProgressRow
	for rows.Next() {
		var i GetCategoryProgressRow
		if err := rows.Scan(&i.Category, &i.Cleared, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGradeDistribution = `-- name: GetGradeDistribution :one
SELECT COUNT(*) FILTER (WHERE grade = 'green')  AS green,
       COUNT(*) FILTER (WHERE grade = 'yellow') AS yellow,
       COUNT(*) FILTER (WHERE grade = 'red')    AS red
FROM progress
WHERE user_id = $1
`

type GetGradeDistributionRow struct {
	Green  int64 `json:"green"`
	Yellow int64 `json:"yellow"`
	Red    int64 `json:"red"`
}

func (q *Queries) GetGradeDistribution(ctx context.Context, userID int64) (GetGradeDistributionRow, error) {
	row := q.db.QueryRow(ctx, getGradeDistribution, userID)
	var i GetGradeDistributionRow
	err := row.Scan(&i.Green, &i.Yellow, &i.Red)
	return i, err
}

const getTotalCleared = `-- name: GetTotalCleared :one
SELECT COUNT(DISTINCT ci.verse_id) AS total
FROM progress p
JOIN course_items ci ON ci.id = p.course_item_id
WHERE p.user_id = $1 AND p.cleared
`

// 같은 구절이 여러 코스에 수록돼 progress 행이 중복돼도 실제 외운 구절 수를 반환.
func (q *Queries) GetTotalCleared(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalCleared, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}
