// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"
)

const getCategoryProgress = `-- name: GetCategoryProgress :many
SELECT c.category AS category,
       COUNT(*) FILTER (WHERE p.cleared) AS cleared,
       COUNT(*)                          AS total
FROM course_items ci
JOIN courses c ON c.id = ci.course_id
LEFT JOIN progress p ON p.course_item_id = ci.id AND p.user_id = $1
GROUP BY c.category
`

type GetCategoryProgressRow struct {
	Category string `json:"category"`
	Cleared  int64  `json:"cleared"`
	Total    int64  `json:"total"`
}

func (q *Queries) GetCategoryProgress(ctx context.Context, userID int64) ([]GetCategoryProgressRow, error) {
	rows, err := q.db.Query(ctx, getCategoryProgress, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryProgressRow
	for rows.Next() {
		var i GetCategoryProgressRow
		if err := rows.Scan(&i.Category, &i.Cleared, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGradeDistribution = `-- name: GetGradeDistribution :one
SELECT COUNT(*) FILTER (WHERE grade = 'green')  AS green,
       COUNT(*) FILTER (WHERE grade = 'yellow') AS yellow,
       COUNT(*) FILTER (WHERE grade = 'red')    AS red
FROM progress
WHERE user_id = $1
`

type GetGradeDistributionRow struct {
	Green  int64 `json:"green"`
	Yellow int64 `json:"yellow"`
	Red    int64 `json:"red"`
}

func (q *Queries) GetGradeDistribution(ctx context.Context, userID int64) (GetGradeDistributionRow, error) {
	row := q.db.QueryRow(ctx, getGradeDistribution, userID)
	var i GetGradeDistributionRow
	err := row.Scan(&i.Green, &i.Yellow, &i.Red)
	return i, err
}

const getTotalCleared = `-- name: GetTotalCleared :one
SELECT COUNT(*) AS total FROM progress WHERE user_id = $1 AND cleared
`

func (q *Queries) GetTotalCleared(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalCleared, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}
