// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppleUser = `-- name: CreateAppleUser :one
INSERT INTO users (username, display_name, password_hash, email, apple_sub)
VALUES ($1, $2, '', $3, $4)
RETURNING id, display_name, password_hash, created_at, username, lives, lives_updated_at, theme, language, display_name_updated_at, email, google_sub, apple_sub
`

type CreateAppleUserParams struct {
	Username    string      `json:"username"`
	DisplayName string      `json:"display_name"`
	Email       pgtype.Text `json:"email"`
	AppleSub    pgtype.Text `json:"apple_sub"`
}

func (q *Queries) CreateAppleUser(ctx context.Context, arg CreateAppleUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createAppleUser,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.AppleSub,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Username,
		&i.Lives,
		&i.LivesUpdatedAt,
		&i.Theme,
		&i.Language,
		&i.DisplayNameUpdatedAt,
		&i.Email,
		&i.GoogleSub,
		&i.AppleSub,
	)
	return i, err
}

const createGoogleUser = `-- name: CreateGoogleUser :one
INSERT INTO users (username, display_name, password_hash, email, google_sub)
VALUES ($1, $2, '', $3, $4)
RETURNING id, display_name, password_hash, created_at, username, lives, lives_updated_at, theme, language, display_name_updated_at, email, google_sub, apple_sub
`

type CreateGoogleUserParams struct {
	Username    string      `json:"username"`
	DisplayName string      `json:"display_name"`
	Email       pgtype.Text `json:"email"`
	GoogleSub   pgtype.Text `json:"google_sub"`
}

func (q *Queries) CreateGoogleUser(ctx context.Context, arg CreateGoogleUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createGoogleUser,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.GoogleSub,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Username,
		&i.Lives,
		&i.LivesUpdatedAt,
		&i.Theme,
		&i.Language,
		&i.DisplayNameUpdatedAt,
		&i.Email,
		&i.GoogleSub,
		&i.AppleSub,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, display_name, password_hash)
VALUES ($1, $2, $3)
RETURNING id, display_name, password_hash, created_at, username, lives, lives_updated_at, theme, language, display_name_updated_at, email, google_sub, apple_sub
`

type CreateUserParams struct {
	Username     string `json:"username"`
	DisplayName  string `json:"display_name"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.DisplayName, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Username,
		&i.Lives,
		&i.LivesUpdatedAt,
		&i.Theme,
		&i.Language,
		&i.DisplayNameUpdatedAt,
		&i.Email,
		&i.GoogleSub,
		&i.AppleSub,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByAppleSub = `-- name: GetUserByAppleSub :one
SELECT id, display_name, password_hash, created_at, username, lives, lives_updated_at, theme, language, display_name_updated_at, email, google_sub, apple_sub FROM users WHERE apple_sub = $1
`

func (q *Queries) GetUserByAppleSub(ctx context.Context, appleSub pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAppleSub, appleSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Username,
		&i.Lives,
		&i.LivesUpdatedAt,
		&i.Theme,
		&i.Language,
		&i.DisplayNameUpdatedAt,
		&i.Email,
		&i.GoogleSub,
		&i.AppleSub,
	)
	return i, err
}

const getUserByGoogleSub = `-- name: GetUserByGoogleSub :one
SELECT id, display_name, password_hash, created_at, username, lives, lives_updated_at, theme, language, display_name_updated_at, email, google_sub, apple_sub FROM users WHERE google_sub = $1
`

func (q *Queries) GetUserByGoogleSub(ctx context.Context, googleSub pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSub, googleSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Username,
		&i.Lives,
		&i.LivesUpdatedAt,
		&i.Theme,
		&i.Language,
		&i.DisplayNameUpdatedAt,
		&i.Email,
		&i.GoogleSub,
		&i.AppleSub,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, display_name, password_hash, created_at, username, lives, lives_updated_at, theme, language, display_name_updated_at, email, google_sub, apple_sub FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Username,
		&i.Lives,
		&i.LivesUpdatedAt,
		&i.Theme,
		&i.Language,
		&i.DisplayNameUpdatedAt,
		&i.Email,
		&i.GoogleSub,
		&i.AppleSub,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, display_name, password_hash, created_at, username, lives, lives_updated_at, theme, language, display_name_updated_at, email, google_sub, apple_sub FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Username,
		&i.Lives,
		&i.LivesUpdatedAt,
		&i.Theme,
		&i.Language,
		&i.DisplayNameUpdatedAt,
		&i.Email,
		&i.GoogleSub,
		&i.AppleSub,
	)
	return i, err
}

const getUserLives = `-- name: GetUserLives :one
SELECT lives, lives_updated_at FROM users WHERE id = $1
`

type GetUserLivesRow struct {
	Lives          int32              `json:"lives"`
	LivesUpdatedAt pgtype.Timestamptz `json:"lives_updated_at"`
}

func (q *Queries) GetUserLives(ctx context.Context, id int64) (GetUserLivesRow, error) {
	row := q.db.QueryRow(ctx, getUserLives, id)
	var i GetUserLivesRow
	err := row.Scan(&i.Lives, &i.LivesUpdatedAt)
	return i, err
}

const updateDisplayName = `-- name: UpdateDisplayName :one
UPDATE users SET display_name = $2, display_name_updated_at = now() WHERE id = $1
RETURNING id, display_name, password_hash, created_at, username, lives, lives_updated_at, theme, language, display_name_updated_at, email, google_sub, apple_sub
`

type UpdateDisplayNameParams struct {
	ID          int64  `json:"id"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateDisplayName, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Username,
		&i.Lives,
		&i.LivesUpdatedAt,
		&i.Theme,
		&i.Language,
		&i.DisplayNameUpdatedAt,
		&i.Email,
		&i.GoogleSub,
		&i.AppleSub,
	)
	return i, err
}

const updateUserLives = `-- name: UpdateUserLives :exec
UPDATE users SET lives = $2, lives_updated_at = $3 WHERE id = $1
`

type UpdateUserLivesParams struct {
	ID             int64              `json:"id"`
	Lives          int32              `json:"lives"`
	LivesUpdatedAt pgtype.Timestamptz `json:"lives_updated_at"`
}

func (q *Queries) UpdateUserLives(ctx context.Context, arg UpdateUserLivesParams) error {
	_, err := q.db.Exec(ctx, updateUserLives, arg.ID, arg.Lives, arg.LivesUpdatedAt)
	return err
}

const updateUserPrefs = `-- name: UpdateUserPrefs :one
UPDATE users SET
  theme = COALESCE($2, theme),
  language = COALESCE($3, language)
WHERE id = $1
RETURNING id, display_name, password_hash, created_at, username, lives, lives_updated_at, theme, language, display_name_updated_at, email, google_sub, apple_sub
`

type UpdateUserPrefsParams struct {
	ID       int64       `json:"id"`
	Theme    pgtype.Text `json:"theme"`
	Language pgtype.Text `json:"language"`
}

func (q *Queries) UpdateUserPrefs(ctx context.Context, arg UpdateUserPrefsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPrefs, arg.ID, arg.Theme, arg.Language)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Username,
		&i.Lives,
		&i.LivesUpdatedAt,
		&i.Theme,
		&i.Language,
		&i.DisplayNameUpdatedAt,
		&i.Email,
		&i.GoogleSub,
		&i.AppleSub,
	)
	return i, err
}
