// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verses.sql

package db

import (
	"context"
)

const getChapter = `-- name: GetChapter :many

SELECT id, book, chapter, verse, text FROM bible_verses WHERE book = $1 AND chapter = $2 ORDER BY verse
`

type GetChapterParams struct {
	Book    int16 `json:"book"`
	Chapter int16 `json:"chapter"`
}

// sqlc 쿼리 정의. 형식: -- name: 쿼리이름 :반환종류
func (q *Queries) GetChapter(ctx context.Context, arg GetChapterParams) ([]BibleVerse, error) {
	rows, err := q.db.Query(ctx, getChapter, arg.Book, arg.Chapter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BibleVerse
	for rows.Next() {
		var i BibleVerse
		if err := rows.Scan(
			&i.ID,
			&i.Book,
			&i.Chapter,
			&i.Verse,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVerse = `-- name: GetVerse :one
SELECT id, book, chapter, verse, text FROM bible_verses WHERE book = $1 AND chapter = $2 AND verse = $3
`

type GetVerseParams struct {
	Book    int16 `json:"book"`
	Chapter int16 `json:"chapter"`
	Verse   int16 `json:"verse"`
}

func (q *Queries) GetVerse(ctx context.Context, arg GetVerseParams) (BibleVerse, error) {
	row := q.db.QueryRow(ctx, getVerse, arg.Book, arg.Chapter, arg.Verse)
	var i BibleVerse
	err := row.Scan(
		&i.ID,
		&i.Book,
		&i.Chapter,
		&i.Verse,
		&i.Text,
	)
	return i, err
}

const listSegmentsByVerse = `-- name: ListSegmentsByVerse :many
SELECT id, verse_id, segment_label, text, word_count, ord FROM verse_segments WHERE verse_id = $1 ORDER BY ord
`

func (q *Queries) ListSegmentsByVerse(ctx context.Context, verseID int64) ([]VerseSegment, error) {
	rows, err := q.db.Query(ctx, listSegmentsByVerse, verseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VerseSegment
	for rows.Next() {
		var i VerseSegment
		if err := rows.Scan(
			&i.ID,
			&i.VerseID,
			&i.SegmentLabel,
			&i.Text,
			&i.WordCount,
			&i.Ord,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
