package main

// messiah_topics_en.go — 메시아 예언 코스의 절별 주제(한글) → 영어 번역.
// messiah_books.go의 고유 topic 303개에 대응한다. 신학 뉘앙스가 있어 자동 생성이 아닌
// 수기 번역이며, 필요 시 감수해 다듬을 수 있다. 미포함 항목은 한글로 폴백된다.
var messiahTopicEn = map[string]string{
	"가난한 자와 믿는 남은 자들을 섬기심":        "He ministers to the poor and the believing remnant",
	"가장 높으시며 영광스러우신 메시야":          "The most high and glorious Messiah",
	"가장 높으신 그분":                   "He is the Most High",
	"갈릴리에서의 그분의 사역":               "His ministry in Galilee",
	"갈보리에서 슬픔과 고난":                "Sorrow and suffering at Calvary",
	"갑작스러운 성전 방문을 하심":             "He suddenly comes to the temple",
	"거절당하신 분":                     "He is rejected",
	"거짓 증인들이 그분을 대적함":             "False witnesses rise against Him",
	"건축자들의 버린 돌이 모퉁이의 머릿돌이 되심":    "The stone the builders rejected becomes the head cornerstone",
	"경멸을 받으심":                     "He is despised",
	"곤고한 자를 쉬게하심":                 "He gives rest to the weary",
	"골고다상의 흑암":                    "Darkness over Golgotha",
	"골고다에서 하실 말씀 '나의 하나님...'":      "His cry at Golgotha, 'My God...'",
	"광풍과 폭풍으로부터 피난처되시는 분":         "A refuge from the storm and tempest",
	"구세주로 출생하심":                   "He is born as Savior",
	"그 분을 믿음으로 생명을 얻음":            "Life through faith in Him",
	"그들의 구속자로 시온에 오심":             "He comes to Zion as their Redeemer",
	"그들이 입술을 삐죽이며 머리를 흔들며 저주함":    "They mock, shake their heads and revile Him",
	"그리스도 안에서 모든 사람이 죽음":          "In Christ all die",
	"그리스도 우리의 유월절":                "Christ our Passover",
	"그리스도, 우리의 친족, 대속자":           "Christ, our kinsman and redeemer",
	"그리스도라 불리우심(메시아 혹은 기름부음을 받으신 분)": "He is called Christ (Messiah, the Anointed One)",
	"그리스도와 그분의 말씀들을 알지못함":         "They do not know Christ or His words",
	"그리스도의 목회와 자유":                "Christ's ministry and freedom",
	"그분 메시야는 좋은 소식을 전하심":          "The Messiah proclaims good news",
	"그분 안에 넘치는 열매들":               "Abundant fruit in Him",
	"그분 위에 계신 하나님의 성령님":           "The Spirit of God rests upon Him",
	"그분께서 가르치심":                   "He teaches",
	"그분께서 너를 구원하러 오시리라":           "He will come to save you",
	"그분께서 모든 인류의 죄를 짊어지심":         "He bears the sin of all mankind",
	"그분께서 모욕을 당하심":                "He is insulted",
	"그분께서 비유로 가르치심":               "He teaches in parables",
	"그분께서 사단의 머리를 깨심":             "He crushes the serpent's head",
	"그분께서 사망을 물리치심":               "He conquers death",
	"그분께서 세상을 위해 죽으심은 하나님의 뜻":     "It is God's will that He die for the world",
	"그분께서 오실 때 이스라엘은 불의한 지도자들이 있을것임": "At His coming Israel has unrighteous leaders",
	"그분께서 율법에따른 제사를 폐지하심":         "He abolishes the sacrifices of the law",
	"그분께서 인류를 구원하시기 위해 생명을 내어주심":   "He gives His life to save mankind",
	"그분께서 재판을 받으심":                "He is put on trial",
	"그분께서 죽임을 당하심":                "He is put to death",
	"그분께서 침뱉음을 당하시고":              "He is spat upon",
	"그분께서 하나님 앞에서 사람을 의롭게 하심":     "He justifies men before God",
	"그분께서 하나님의 성령님을 보내심":          "He sends the Spirit of God",
	"그분께서 하나님의 지혜와 권위로 말씀하심":      "He speaks with God's wisdom and authority",
	"그분께서 헤롯 성전을 방문하심":            "He visits Herod's temple",
	"그분께서는 거룩하신 분":                "He is holy",
	"그분은 구원하시러 오심":                "He comes to save",
	"그분은 모든 세상과 함께 하심":            "He is with all the world",
	"그분은 세상의 죄들을 짊어지심":            "He bears the sins of the world",
	"그분은 열방의 빛이심":                 "He is the light of the nations",
	"그분은 오직 단 한분이신 구세주이심":         "He is the one and only Savior",
	"그분은 외치지 아니하며 높히지 아니하시며":      "He does not cry out or lift up His voice",
	"그분은 이스라엘의 구원주이시다":            "He is the Savior of Israel",
	"그분은 진실로 하나님이시다":              "He is truly God",
	"그분은 질고를 치료하심":                "He heals our sicknesses",
	"그분은 참 하나님이시며 참 사람이심":         "He is true God and true man",
	"그분은 참된 선지자":                  "He is the true prophet",
	"그분은 하늘에 오르심":                 "He ascends into heaven",
	"그분을 거절한 자들에게 사역을 멈추심":        "He ceases His ministry to those who reject Him",
	"그분을 거절함으로 하나님께서도 그들을 버리심":    "Because they reject Him, God also forsakes them",
	"그분을 때리는 자에게 뺨을 맡기며":          "He gives His cheek to those who strike Him",
	"그분을 아는 자들로부터 멸시받음":           "He is despised by those who know Him",
	"그분을 죽이자는 모략들":                "Plots to kill Him",
	"그분을 찾는 자들이 동산까지 옴":           "Those seeking Him come to the garden",
	"그분을 통해 모든 민족이 복을 받음":         "Through Him all nations are blessed",
	"그분의 거룩하시고 선하심":               "His holiness and goodness",
	"그분의 고난과 갈보리의 멸시받으심":          "His suffering and the scorn of Calvary",
	"그분의 고소자들 앞에서 입을 다무심":         "He is silent before His accusers",
	"그분의 공의로우신 심판":                "His righteous judgment",
	"그분의 공의로우심":                   "His righteousness",
	"그분의 교회를 사랑하심":                "He loves His church",
	"그분의 긍휼하신 성품":                 "His compassionate nature",
	"그분의 등이 채찍에 찢기심":              "His back is torn by scourging",
	"그분의 떡을 받은 친구가 배반함":           "A friend who shared His bread betrays Him",
	"그분의 말씀을 백성이 순종치 않음":          "The people do not obey His word",
	"그분의 멸시받으심과 높임을 받으심":          "He is despised and yet exalted",
	"그분의 목마르심":                    "His thirst",
	"그분의 백성들에게 70주를 언약하심":         "He covenants seventy weeks to His people",
	"그분의 백성들이 그분을 믿지 아니함":         "His people do not believe in Him",
	"그분의 보혈로 모든 속죄가 이루어짐":         "All atonement is accomplished by His blood",
	"그분의 부활하심":                    "His resurrection",
	"그분의 부활하심의 즐거움":               "The joy of His resurrection",
	"그분의 뼈가 꺽이지 아니하심":             "None of His bones are broken",
	"그분의 뼈는 부서지지 아니함":             "His bones are not broken",
	"그분의 성결하심과 거룩하심":              "His purity and holiness",
	"그분의 손목과 발목이 찔리심":             "His hands and feet are pierced",
	"그분의 승천에 대한 예시":               "A foreshadowing of His ascension",
	"그분의 아는 자를 멀리 있게 하심":          "He puts His acquaintances far from Him",
	"그분의 열매가 넘침":                  "His fruit overflows",
	"그분의 열매는 풍성하심":                "His fruit is abundant",
	"그분의 옷이 제비뽑히고 나누임":            "His garments are divided and cast lots for",
	"그분의 육체가 승천하심":                "His body ascends",
	"그분의 이름을 믿는 자들의 권세":           "Authority to those who believe in His name",
	"그분의 입술에는 궤사가 없으심":            "No deceit is found in His lips",
	"그분의 입술에서 나오는 은혜의 말씀들":        "Gracious words from His lips",
	"그분의 죽으심과 심장의 깨어지심":           "His death and the breaking of His heart",
	"그분의 지혜와 지각능력":                "His wisdom and discernment",
	"그분의 진리와 공의로우심":               "His truth and righteousness",
	"그분의 찬송받으실 이름은 예수라":           "His praised name is Jesus",
	"그분의 초림의 때":                   "The time of His first coming",
	"그분의 친구들도 돌아섬":                "Even His friends turn away",
	"그분의 통치권은 영원하심":               "His dominion is everlasting",
	"그분의 한 이름 하나님 혹은 엘로힘":         "One of His names is God, or Elohim",
	"그분의 호칭 '실로'":                 "His title 'Shiloh'",
	"그분의 희생으로 유대 성전이 무용하게됨":       "By His sacrifice the Jewish temple becomes obsolete",
	"그분의 희생으로 하나님께서 높혀 주심":        "God exalts Him for His sacrifice",
	"극한 폭력을 당하시고 희생하심":            "He suffers extreme violence and is sacrificed",
	"기름부음을 받으신 왕":                 "The anointed King",
	"기묘자라, 모사(謀士)라":               "Wonderful, Counselor",
	"깨끗하게 하시는 사역":                 "His cleansing ministry",
	"깨닫지 못하는 귀들":                  "Ears that do not understand",
	"끝이 없으신 그분의 나라, 평화, 보좌":       "His kingdom, peace and throne without end",
	"나귀새끼를 타시고 예루살렘에 입성하심":        "He enters Jerusalem riding on a donkey's colt",
	"나는 선한 목자라":                   "I am the good shepherd",
	"나는 스스로 있느니라(I AM)":            "I AM",
	"나를 때리는 자에게 등을 돌려주며":          "He gives His back to those who strike Him",
	"나무에 달리시고 부활하심":               "He hangs on a tree and rises",
	"나무에 달린 자는 저주받음":              "Cursed is everyone who hangs on a tree",
	"나병을 정결케 하는 대제사장":             "The High Priest who cleanses leprosy",
	"나사렛 사람이라 불리우리라":              "He shall be called a Nazarene",
	"나의 영혼을 주님의 손에 맡기나이다":         "Into Your hands I commit my spirit",
	"나의 혼의 곤고함이 넘침":               "The anguish of His soul overflows",
	"너는 내 아들이라 내가 너를 낳았도다":        "You are My Son; today I have begotten You",
	"너희 하나님을 보라":                  "Behold your God",
	"다 이루었다":                      "It is finished",
	"다른 죄인들같이 버림받으심":              "He is forsaken like other sinners",
	"다윗의 씨":                       "The seed of David",
	"다윗의 씨(그 몸의 열매)":              "The seed of David (the fruit of his body)",
	"다윗의 씨, 보라, 왕권이 영원하심":         "The seed of David; behold, His kingship is everlasting",
	"다윗의 아들":                      "The Son of David",
	"다윗의 아들이 주님이라 불리우심":           "David's Son is called Lord",
	"다윗의 왕좌에 앉으심":                 "He sits on David's throne",
	"다윗의 집을 세우심":                  "He establishes the house of David",
	"다윗의 후손":                      "A descendant of David",
	"다윗의 후손 (겔17)":                "A descendant of David (Ezek. 17)",
	"다윗의 후손 (겔34)":                "A descendant of David (Ezek. 34)",
	"다윗의 후손 (렘33)":                "A descendant of David (Jer. 33)",
	"땅끝까지 구원을 베푸심":                "He brings salvation to the ends of the earth",
	"맹인의 눈을 뜨게 하심":                "He opens the eyes of the blind",
	"메시아의 부활을 예언하심":               "The resurrection of the Messiah foretold",
	"메시야께서 공의로 행하심":               "The Messiah acts in righteousness",
	"메시야께서 구원을 선물하심":              "The Messiah gives salvation as a gift",
	"메시야께서 낮아지심":                  "The Messiah is humbled",
	"메시야는 곧 하나님이심":                "The Messiah is God",
	"메시야는 곧 하나님이심 (슥11:12)":       "The Messiah is God (Zech. 11:12)",
	"메시야는 귀하신 기초돌이 되심":            "The Messiah becomes the precious foundation stone",
	"메시야는 새 약속이 되심":               "The Messiah becomes the new covenant",
	"메시야는 이스라엘에게 거절당하심":           "The Messiah is rejected by Israel",
	"메시야는 참 하나님과 참 사람이 되심":        "The Messiah is true God and true man",
	"메시야는 참 하나님이시며 참 사람이심":        "The Messiah is true God and true man",
	"메시야는 하나님이심":                  "The Messiah is God",
	"메시야를 위한 길을 예비하는 사자":          "A messenger who prepares the way for the Messiah",
	"메시야의 영혼의 곤고하심":               "The anguish of the Messiah's soul",
	"메시야의 육체가 못박히심":               "The Messiah's body is nailed to the cross",
	"멜기세덱의 반열의 대제사장":              "A High Priest in the order of Melchizedek",
	"모든 민족들을 향하신 그분의 새 언약":        "His new covenant for all nations",
	"모든 민족들이 그분의 가르침을 배움":         "All nations learn His teaching",
	"모든 인류를 위해 죄를 지고 가심":          "He bears away the sin of all mankind",
	"모든 인류를 위해 죄를 지고 가져가심":        "He carries away the sin of all mankind",
	"모든 인류에게 구원을 선물하심":            "He gives salvation to all mankind",
	"모든 형벌을 담당하심":                 "He bears all the punishment",
	"모세를 믿었더면 나를 믿으리라":            "If you believed Moses, you would believe Me",
	"모욕과 괴로움을 받으심":                "He suffers insult and affliction",
	"모퉁이 기초돌 되시는 분":               "He is the chief cornerstone",
	"무고히 미움 받으심":                  "He is hated without cause",
	"민족으로부터 경멸당하심":                "He is despised by the nation",
	"반역하지 아니하시는 종":                "The servant who does not rebel",
	"받들어 높임을 받으신 종":               "The servant who is exalted and lifted up",
	"배반자의 죽음":                     "The death of the betrayer",
	"베들레헴에서 태어나심":                 "He is born in Bethlehem",
	"보라 나의 종을...":                 "Behold My servant...",
	"보라 왕이 오신다":                   "Behold, the King comes",
	"보혈에 의한 속죄":                   "Atonement by His blood",
	"복중에서부터 불러내심":                 "Called from the womb",
	"복중에서부터 종으로 부르심":              "Called as a servant from the womb",
	"부자의 무덤에 묻히심":                 "He is buried in a rich man's tomb",
	"부활시키시는 그분의 능력":               "His power to raise the dead",
	"부활의 예표":                      "A type of the resurrection",
	"부활하셔서 영원히 살아계심":              "He rises and lives forever",
	"부활하심으로 사망을 폐하심":              "By His resurrection He abolishes death",
	"사단의 능력과 지옥의 능력을 파괴하심":        "He destroys the power of Satan and hell",
	"사람과 같이 낮추신 분":                "He humbled Himself as a man",
	"사람과 하나님의 평화의 중보자":            "The mediator of peace between God and man",
	"사람들 앞에서 벌거벗기움을 당하심":          "He is stripped naked before men",
	"사람들에게 주신 은사들":                "Gifts given to men",
	"사람들이 그분에게 순종할 것임":            "People will obey Him",
	"산돌을 세우시는 반석":                 "The rock that sets the living stone",
	"상처받은 종":                      "The wounded servant",
	"상한 갈대와 꺼져가는 심지를 끄지 아니하심":     "He does not break a bruised reed or quench a smoldering wick",
	"새 언약의 전파자":                   "The herald of the new covenant",
	"생명의 꼴을 먹이시는 목자":              "The shepherd who feeds with the food of life",
	"선구자는 많은 사람을 의롭게하심":           "The forerunner justifies many",
	"성령님의 기름부으심":                  "The anointing of the Holy Spirit",
	"세상의 죄들을 담당하신 죽으심":            "His death bearing the sins of the world",
	"세상죄를 위해 죽으심":                 "He dies for the sin of the world",
	"셈의 하나님의 셈의 아들":               "A son of Shem, of the God of Shem",
	"스룹바벨의 후손":                    "A descendant of Zerubbabel",
	"식초를 마시우게 줌":                  "He is given vinegar to drink",
	"썩지 아니하심을 보심":                 "He sees no corruption",
	"아버지의 뜻을 따르심":                 "He follows the Father's will",
	"아브라함의 씨 모든 민족이 복을 받음":        "The seed of Abraham; all nations are blessed",
	"아브라함의 씨를 세우실 약속":             "The promise to establish the seed of Abraham",
	"악인들과 함께 처형 받으심":              "He is executed with the wicked",
	"애매히 미움받으심":                   "He is hated without cause",
	"어린 양의 보혈로 구원을 받음":            "Salvation through the blood of the Lamb",
	"어린 양의 뼈가 꺽이지 않음":             "Not a bone of the Lamb is broken",
	"어린아이들의 입술이 찬송드림":             "Out of the mouths of children comes praise",
	"엘리야의 영이 있는 선구자":              "The forerunner in the spirit of Elijah",
	"여자의 씨(처녀의 출산)":               "The seed of the woman (the virgin birth)",
	"열방이 그분께로 오실것이요":              "The nations will come to Him",
	"열방이 놀라는 종의 말씀 선포":            "The servant's proclamation that astonishes the nations",
	"영문 박에 뿌려진 피":                 "Blood sprinkled outside the camp",
	"영원부터 계신 분":                   "He is from everlasting",
	"영원으로부터 오신 주님":                "The Lord who comes from eternity",
	"영원하신 왕국":                     "An everlasting kingdom",
	"영존하신 아버지":                    "The Everlasting Father",
	"예루살렘에서 즐거움으로 영접받으심":          "He is welcomed with joy in Jerusalem",
	"예수님은 구원이라고 불리우심":             "Jesus is called Salvation",
	"예수님의 부활":                     "The resurrection of Jesus",
	"오묘하신 말씀":                     "Words of mystery",
	"왕들이 다윗의 씨를 영접함":              "Kings receive the seed of David",
	"외치는 자를 보내심":                  "He sends one who cries out",
	"우리의 보기에 아름다움이 없으신 분":         "He has no beauty that we should desire Him",
	"위험에서 승리하신 그리스도":              "Christ victorious over danger",
	"유다의 씨":                       "The seed of Judah",
	"유대인들로부터 잃어버리심":               "He is lost from among the Jews",
	"육체의 생명은 피":                   "The life of the flesh is in the blood",
	"은 30량에 배반당하심":                "He is betrayed for thirty pieces of silver",
	"은 30이 성전 앞에 던져짐":             "The thirty pieces of silver are cast down before the temple",
	"은혜와 긍휼이 많으심":                 "He is full of grace and mercy",
	"은혜의 시대를 선포하심":                "He proclaims the age of grace",
	"이방인의 빛(구세주)":                 "A light to the Gentiles (the Savior)",
	"이사야가 본 그분의 영광":               "His glory that Isaiah saw",
	"이삭의 씨 모든 민족이 복을 받을 것임":       "The seed of Isaac; all nations will be blessed",
	"이삭의 씨(약속의 씨)":                "The seed of Isaac (the promised seed)",
	"이삭의 씨의 약속":                   "The promise of the seed of Isaac",
	"이새의 가지, 이새의 아들":              "The Branch of Jesse, the son of Jesse",
	"이스라엘로부터 거절당하심":               "He is rejected by Israel",
	"이스라엘에게 그분의 공의를 선포하심":         "He proclaims His righteousness to Israel",
	"이스라엘을 복주심":                   "He blesses Israel",
	"이스라엘의 불신이 메시야로 하여금 그들을 거절하게 하심": "Israel's unbelief leads the Messiah to reject them",
	"이스라엘의 영적 반석":                 "The spiritual rock of Israel",
	"이스라엘이 그분을 거절함으로 하나님께서도 그들의 보호를 거두심": "Because Israel rejects Him, God withdraws His protection from them",
	"이스라엘이 그분을 거절함으로 흩어짐":         "Because they reject Him, Israel is scattered",
	"이스라엘이 다른 왕을 기다리며 그분을 거절함":     "Israel awaits another king and rejects Him",
	"임마누엘 -하나님께서 우리와 함께 하심":       "Immanuel — God with us",
	"임마누엘 하나님. 왕들 중에 가장 크신 분":     "Immanuel, God; the greatest among kings",
	"임마누엘이라 불리우심":                 "He is called Immanuel",
	"장대에 달린 놋뱀, 예수 그리스도를 쳐다봄":     "The bronze serpent on the pole, looking to Jesus Christ",
	"전능하신 하나님":                    "The Mighty God",
	"전제 예물, 누구든지 목마르거든":           "The drink offering; whoever is thirsty",
	"제사장이시며 왕이심":                  "He is Priest and King",
	"조롱을 받으심":                     "He is mocked",
	"죄 없으시며 폭력을 행하시지 않으심":         "He is without sin and does no violence",
	"죄를 끝내심":                      "He puts an end to sin",
	"죄를 위한 단 한 분의 희생예물":           "The one sacrifice for sin",
	"죄와 사망의 구속으로부터 자유케하심":         "He frees us from the bondage of sin and death",
	"주님의 승천하심":                    "The ascension of the Lord",
	"주님의 집에 대한 열심":                "Zeal for the house of the Lord",
	"죽음에서 그분의 부활하심":               "His resurrection from the dead",
	"죽음에서 일어나심":                   "He rises from the dead",
	"지금은 아니나 내가 그분을 보리라":          "Not now, but I shall see Him",
	"지혜로우시고 오묘하신 말씀":              "Wise and mysterious words",
	"지혜자들이 그분을 방문함":               "Wise men visit Him",
	"창조주의 아들은 메시아이심":              "The Son of the Creator is the Messiah",
	"처음과 끝이 되시는 분":                "He is the First and the Last",
	"체포되시고 심문 당하심":                "He is arrested and interrogated",
	"최고의 높이 올려지심":                 "He is lifted up to the highest",
	"최후의 만찬":                      "The Last Supper",
	"큰 통곡으로 우시는 분":                "He weeps with loud cries",
	"타인이 아닌 친구로부터 버림받으심":          "He is forsaken by a friend, not a stranger",
	"평강의 왕이시라":                    "He is the Prince of Peace",
	"평화와 좋은 소식을 가져오시는 분":          "He brings peace and good news",
	"하나님 아들의 능력":                  "The power of the Son of God",
	"하나님 우편에 앉으심":                 "He sits at the right hand of God",
	"하나님과 사람 사이의 중보자":             "The mediator between God and man",
	"하나님과 사람의 중보자 되심":             "He becomes the mediator between God and man",
	"하나님께 향하신 그분의 호소":             "His appeal to God",
	"하나님께서 건져주실 것을 믿으심":           "He trusts that God will deliver Him",
	"하나님께서 구원자를 고난에 내어주심":         "God gives the Savior over to suffering",
	"하나님께서 아들로 오심":                "God comes as the Son",
	"하나님에 의해 부활하심":                "He is raised by God",
	"하나님으로부터 끊어짐을 당하심":            "He is cut off from God",
	"하나님은 그분의 예물과 고통받으심을 만족하셨음":    "God is satisfied with His offering and suffering",
	"하나님의 기뻐하시는 종":                "The servant in whom God delights",
	"하나님의 뜻은 그분께서 세상 죄를 담당하시는 것":   "It is God's will that He bear the sin of the world",
	"하나님의 뜻은 그분께서 인류를 위해 희생하시는 것임":  "It is God's will that He be sacrificed for mankind",
	"하나님의 아들":                     "The Son of God",
	"하나님의 어린 양 약속":                "The promise of the Lamb of God",
	"하나님의 어린 양(희생예물)":             "The Lamb of God (the sacrifice)",
	"하나님의 종":                      "The servant of God",
	"하나님의 집에 서신 주님":               "The Lord standing in the house of God",
	"하늘로 승천하심":                    "He ascends into heaven",
	"하늘을 흑암과 굵은 베로 덮히심":           "The heavens are clothed with darkness and sackcloth",
	"한 분의 왕":                      "One King",
	"한 아이로 태어나심":                  "He is born as a child",
	"한 증인이 되심":                    "He becomes a witness",
	"한 처녀가 아들을 낳을 것이요":            "A virgin will bear a son",
	"한 처녀로부터 나심":                  "He is born of a virgin",
	"한 특별하신 성령님의 기름부으심":           "A special anointing of the Holy Spirit",
	"함께 한 자들도 그분을 버림":             "Even His companions forsake Him",
	"형제들에게 외면당하심":                 "He is disowned by His brothers",
	"흠없는 어린 양":                    "The Lamb without blemish",
}
