export interface RefRow {
  ref: string;
  topic: string;
  topic_en: string;
  fulfilled: string;
  fulfilled_en: string;
}

export interface RefSection {
  title: string;
  title_en: string;
  rows: RefRow[];
}

export const messiahReference: RefSection[] = [
  {
    title: "1. 창세기 — 인류 역사 창조와 아브라함의 씨 예수 그리스도",
    title_en: "1. Genesis — Creation of Human History and the Seed of Abraham, Jesus Christ",
    rows: [
      { ref: "3:15", topic: "여자의 씨(처녀의 출산)", topic_en: "Seed of a woman (virgin birth)", fulfilled: "눅1:35, 마1:18-20", fulfilled_en: "Luke 1:35, Matt 1:18-20" },
      { ref: "3:15", topic: "그분께서 사단의 머리를 깨심", topic_en: "He will crush the head of Satan", fulfilled: "히2:14, 요일 3:8", fulfilled_en: "Heb 2:14, 1 John 3:8" },
      { ref: "5:24", topic: "그분의 육체가 승천하심", topic_en: "His bodily ascension", fulfilled: "막16:19", fulfilled_en: "Mark 16:19" },
      { ref: "9:26-27", topic: "셈의 하나님의 셈의 아들", topic_en: "Son of Shem, God of Shem", fulfilled: "눅3:36", fulfilled_en: "Luke 3:36" },
      { ref: "12:3", topic: "아브라함의 씨 모든 민족이 복을 받음", topic_en: "All nations blessed through the seed of Abraham", fulfilled: "행3:25-26", fulfilled_en: "Acts 3:25-26" },
      { ref: "12:7", topic: "아브라함의 씨를 세우실 약속", topic_en: "Promise to establish the seed of Abraham", fulfilled: "갈3:16", fulfilled_en: "Gal 3:16" },
      { ref: "14:18", topic: "한 분의 왕", topic_en: "A king", fulfilled: "히7:2", fulfilled_en: "Heb 7:2" },
      { ref: "14:18", topic: "최후의 만찬", topic_en: "The Last Supper", fulfilled: "마26:26-29", fulfilled_en: "Matt 26:26-29" },
      { ref: "17:19", topic: "이삭의 씨(약속의 씨)", topic_en: "Seed of Isaac (the promised seed)", fulfilled: "롬9:7", fulfilled_en: "Rom 9:7" },
      { ref: "22:8", topic: "하나님의 어린 양 약속", topic_en: "Promise of God's Lamb", fulfilled: "요1:29", fulfilled_en: "John 1:29" },
      { ref: "22:18", topic: "이삭의 씨 모든 민족이 복을 받을 것임", topic_en: "All nations blessed through the seed of Isaac", fulfilled: "갈3:16", fulfilled_en: "Gal 3:16" },
      { ref: "26:2-5", topic: "이삭의 씨의 약속", topic_en: "Promise of the seed of Isaac", fulfilled: "히11:18", fulfilled_en: "Heb 11:18" },
      { ref: "49:10", topic: "그분의 초림의 때", topic_en: "The time of His first coming", fulfilled: "눅2:1-7, 갈4:4", fulfilled_en: "Luke 2:1-7, Gal 4:4" },
      { ref: "49:10", topic: "그분의 호칭 '실로'", topic_en: "His title 'Shiloh'", fulfilled: "요17:3", fulfilled_en: "John 17:3" },
      { ref: "49:10", topic: "유다의 씨", topic_en: "Seed of Judah", fulfilled: "눅3:32", fulfilled_en: "Luke 3:32" },
      { ref: "49:10", topic: "유대인들로부터 잃어버리심", topic_en: "Lost among the Jews", fulfilled: "요11:47-52", fulfilled_en: "John 11:47-52" },
      { ref: "49:10", topic: "사람들이 그분에게 순종할 것임", topic_en: "People will obey Him", fulfilled: "요10:16", fulfilled_en: "John 10:16" },
    ],
  },
  {
    title: "2. 출애굽기 — 하나님의 어린 양과 유월절, 예수 그리스도",
    title_en: "2. Exodus — The Lamb of God and the Passover, Jesus Christ",
    rows: [
      { ref: "3:13-14", topic: "나는 스스로 있느니라(I AM)", topic_en: "I AM THAT I AM", fulfilled: "요4:26", fulfilled_en: "John 4:26" },
      { ref: "12:5", topic: "흠없는 어린 양", topic_en: "A lamb without blemish", fulfilled: "벧전 1:19", fulfilled_en: "1 Pet 1:19" },
      { ref: "12:13", topic: "어린 양의 보혈로 구원을 받음", topic_en: "Saved by the blood of the Lamb", fulfilled: "롬5:8", fulfilled_en: "Rom 5:8" },
      { ref: "12:21-27", topic: "그리스도 우리의 유월절", topic_en: "Christ our Passover", fulfilled: "고전5:7", fulfilled_en: "1 Cor 5:7" },
      { ref: "12:46", topic: "어린 양의 뼈가 꺽이지 않음", topic_en: "No bone of the Lamb broken", fulfilled: "요19:31-36", fulfilled_en: "John 19:31-36" },
      { ref: "15:2", topic: "그분의 찬송받으실 이름은 예수라", topic_en: "His name to be praised is Jesus", fulfilled: "행7:55-56", fulfilled_en: "Acts 7:55-56" },
      { ref: "15:11", topic: "그분의 성결하심과 거룩하심", topic_en: "His purity and holiness", fulfilled: "눅1:35 행4:27", fulfilled_en: "Luke 1:35, Acts 4:27" },
      { ref: "17:6", topic: "이스라엘의 영적 반석", topic_en: "The spiritual Rock of Israel", fulfilled: "고전10:4", fulfilled_en: "1 Cor 10:4" },
      { ref: "33:19", topic: "그분의 긍휼하신 성품", topic_en: "His merciful character", fulfilled: "눅1:72", fulfilled_en: "Luke 1:72" },
    ],
  },
  {
    title: "3. 레위기 — 하나님의 속죄제 희생예물 예수 그리스도",
    title_en: "3. Leviticus — The Sin Offering and Sacrifice of God, Jesus Christ",
    rows: [
      { ref: "14:11", topic: "나병을 정결케 하는 대제사장", topic_en: "The High Priest who cleanses leprosy", fulfilled: "눅5:12-14", fulfilled_en: "Luke 5:12-14" },
      { ref: "16:15-17", topic: "그리스도 안에서 모든 사람이 죽음", topic_en: "All died in Christ", fulfilled: "히9:7-14", fulfilled_en: "Heb 9:7-14" },
      { ref: "16:27", topic: "영문 박에 뿌려진 피", topic_en: "Blood sprinkled outside the camp", fulfilled: "마27:33 히13:11-12", fulfilled_en: "Matt 27:33, Heb 13:11-12" },
      { ref: "17:11", topic: "육체의 생명은 피", topic_en: "Life of the flesh is in the blood", fulfilled: "마26:28 막10:45", fulfilled_en: "Matt 26:28, Mark 10:45" },
      { ref: "17:11", topic: "보혈에 의한 속죄", topic_en: "Atonement through His blood", fulfilled: "요일3:14-18", fulfilled_en: "1 John 3:14-18" },
      { ref: "23:36-37", topic: "전제 예물, 누구든지 목마르거든", topic_en: "Drink offering — if anyone thirsts", fulfilled: "요19:31-36", fulfilled_en: "John 19:31-36" },
    ],
  },
  {
    title: "4. 민수기 — 예수님과 그분의 백성들(교회)의 행진",
    title_en: "4. Numbers — The March of Jesus and His People (the Church)",
    rows: [
      { ref: "9:12", topic: "그분의 뼈는 부서지지 아니함", topic_en: "No bone of His broken", fulfilled: "요19:31-36", fulfilled_en: "John 19:31-36" },
      { ref: "21:9", topic: "장대에 달린 놋뱀, 예수 그리스도를 쳐다봄", topic_en: "Bronze serpent on a pole — look to Jesus Christ", fulfilled: "요3:14-18", fulfilled_en: "John 3:14-18" },
      { ref: "24:17", topic: "지금은 아니나 내가 그분을 보리라", topic_en: "Not now, but I shall see Him", fulfilled: "갈4:4", fulfilled_en: "Gal 4:4" },
    ],
  },
  {
    title: "5. 신명기 — 새김질해야할 예수 그리스도의 계명",
    title_en: "5. Deuteronomy — The Commandments of Jesus Christ to Be Engraved",
    rows: [
      { ref: "18:15", topic: "그분은 참된 선지자", topic_en: "He is the true Prophet", fulfilled: "요6:14", fulfilled_en: "John 6:14" },
      { ref: "18:15-16", topic: "모세를 믿었더면 나를 믿으리라", topic_en: "If you had believed Moses, you would believe Me", fulfilled: "요5:45-47", fulfilled_en: "John 5:45-47" },
      { ref: "21:33", topic: "나무에 달린 자는 저주받음", topic_en: "Cursed is everyone who hangs on a tree", fulfilled: "갈3:10-13", fulfilled_en: "Gal 3:10-13" },
    ],
  },
  {
    title: "룻기",
    title_en: "Ruth",
    rows: [
      { ref: "4:4-9", topic: "그리스도, 우리의 친족, 대속자", topic_en: "Christ, our kinsman-redeemer", fulfilled: "엡1:3-7", fulfilled_en: "Eph 1:3-7" },
    ],
  },
  {
    title: "사무엘상",
    title_en: "1 Samuel",
    rows: [
      { ref: "2:10", topic: "기름부음을 받으신 왕", topic_en: "The anointed King", fulfilled: "마28:18 요12:15, 마3:13-17", fulfilled_en: "Matt 28:18, John 12:15, Matt 3:13-17" },
    ],
  },
  {
    title: "사무엘하",
    title_en: "2 Samuel",
    rows: [
      { ref: "7:12", topic: "다윗의 씨", topic_en: "Seed of David", fulfilled: "마1:1", fulfilled_en: "Matt 1:1" },
      { ref: "7:14", topic: "하나님의 아들", topic_en: "Son of God", fulfilled: "눅1:32", fulfilled_en: "Luke 1:32" },
      { ref: "7:16", topic: "다윗의 집을 세우심", topic_en: "Establishing the house of David", fulfilled: "눅3:31, 계22:16", fulfilled_en: "Luke 3:31, Rev 22:16" },
    ],
  },
  {
    title: "열왕기하",
    title_en: "2 Kings",
    rows: [
      { ref: "2:11", topic: "하늘로 승천하심", topic_en: "Ascension into heaven", fulfilled: "눅24:51", fulfilled_en: "Luke 24:51" },
    ],
  },
  {
    title: "역대상",
    title_en: "1 Chronicles",
    rows: [
      { ref: "17:11", topic: "다윗의 씨", topic_en: "Seed of David", fulfilled: "마1:1, 9:27", fulfilled_en: "Matt 1:1, 9:27" },
      { ref: "17:12-13", topic: "다윗의 왕좌에 앉으심", topic_en: "Seated on the throne of David", fulfilled: "눅1:32-33", fulfilled_en: "Luke 1:32-33" },
    ],
  },
  {
    title: "욥기",
    title_en: "Job",
    rows: [
      { ref: "19:23-27", topic: "예수님의 부활", topic_en: "The resurrection of Jesus", fulfilled: "요5:24-29", fulfilled_en: "John 5:24-29" },
    ],
  },
  {
    title: "6. 시편 — 여호와는 나의 목자시니",
    title_en: "6. Psalms — The LORD Is My Shepherd",
    rows: [
      { ref: "2:7", topic: "너는 내 아들이라 내가 너를 낳았도다", topic_en: "You are My Son; today I have begotten You", fulfilled: "마3:17", fulfilled_en: "Matt 3:17" },
      { ref: "2:7-8", topic: "나무에 달리시고 부활하심", topic_en: "Hung on a tree and raised again", fulfilled: "행13:29-33", fulfilled_en: "Acts 13:29-33" },
      { ref: "2:12", topic: "그 분을 믿음으로 생명을 얻음", topic_en: "Life obtained by believing in Him", fulfilled: "요20:31", fulfilled_en: "John 20:31" },
      { ref: "8:2", topic: "어린아이들의 입술이 찬송드림", topic_en: "Praise from the lips of children", fulfilled: "마21:16", fulfilled_en: "Matt 21:16" },
      { ref: "8:5-6", topic: "그분의 멸시받으심과 높임을 받으심", topic_en: "His humiliation and exaltation", fulfilled: "눅20:50-53, 고전15:27", fulfilled_en: "Luke 20:50-53, 1 Cor 15:27" },
      { ref: "16:10", topic: "썩지 아니하심을 보심", topic_en: "Not abandoned to see decay", fulfilled: "행2:31", fulfilled_en: "Acts 2:31" },
      { ref: "16:9-11", topic: "죽음에서 일어나심", topic_en: "Rising from the dead", fulfilled: "요20:9", fulfilled_en: "John 20:9" },
      { ref: "17:15", topic: "부활의 예표", topic_en: "Foreshadowing of the resurrection", fulfilled: "눅24:6", fulfilled_en: "Luke 24:6" },
      { ref: "22:1", topic: "다른 죄인들같이 버림받으심", topic_en: "Forsaken like other sinners", fulfilled: "고후5:21", fulfilled_en: "2 Cor 5:21" },
      { ref: "22:1", topic: "골고다에서 하실 말씀 '나의 하나님...'", topic_en: "Words at Golgotha: 'My God...'", fulfilled: "막15:34", fulfilled_en: "Mark 15:34" },
      { ref: "22:2", topic: "골고다상의 흑암", topic_en: "Darkness at Golgotha", fulfilled: "마27:45", fulfilled_en: "Matt 27:45" },
      { ref: "22:7", topic: "그들이 입술을 삐죽이며 머리를 흔들며 저주함", topic_en: "They sneer, shake their heads, and mock", fulfilled: "마27:39", fulfilled_en: "Matt 27:39" },
      { ref: "22:8", topic: "그분은 진실로 하나님이시다", topic_en: "He truly is God", fulfilled: "마27:43", fulfilled_en: "Matt 27:43" },
      { ref: "22:9", topic: "구세주로 출생하심", topic_en: "Born as Savior", fulfilled: "눅2:7", fulfilled_en: "Luke 2:7" },
      { ref: "22:14", topic: "그분의 죽으심과 심장의 깨어지심", topic_en: "His death and the breaking of His heart", fulfilled: "요19:34", fulfilled_en: "John 19:34" },
      { ref: "22:14-15", topic: "갈보리에서 슬픔과 고난", topic_en: "Sorrow and suffering at Calvary", fulfilled: "마15:34-37", fulfilled_en: "Matt 15:34-37" },
      { ref: "22:15", topic: "그분의 목마르심", topic_en: "His thirst", fulfilled: "요19:28", fulfilled_en: "John 19:28" },
      { ref: "22:16", topic: "그분의 손목과 발목이 찔리심", topic_en: "His hands and feet pierced", fulfilled: "요19:34, 37 20:27", fulfilled_en: "John 19:34, 37, 20:27" },
      { ref: "22:17-18", topic: "사람들 앞에서 벌거벗기움을 당하심", topic_en: "Stripped naked before the people", fulfilled: "눅23:34-35", fulfilled_en: "Luke 23:34-35" },
      { ref: "22:18", topic: "그분의 옷이 제비뽑히고 나누임", topic_en: "His garments divided and lots cast", fulfilled: "요19:23-24", fulfilled_en: "John 19:23-24" },
      { ref: "22:20-21", topic: "하나님께 향하신 그분의 호소", topic_en: "His appeal to God", fulfilled: "눅23:46", fulfilled_en: "Luke 23:46" },
      { ref: "22:20-21", topic: "사단의 능력과 지옥의 능력을 파괴하심", topic_en: "Destroying the power of Satan and hell", fulfilled: "히2:14", fulfilled_en: "Heb 2:14" },
      { ref: "22:22", topic: "죽음에서 그분의 부활하심", topic_en: "His resurrection from death", fulfilled: "요20:17", fulfilled_en: "John 20:17" },
      { ref: "22:27", topic: "모든 민족들을 향하신 그분의 새 언약", topic_en: "His new covenant for all nations", fulfilled: "골1:16", fulfilled_en: "Col 1:16" },
      { ref: "22:31", topic: "다 이루었다", topic_en: "It is finished", fulfilled: "요19:30", fulfilled_en: "John 19:30" },
      { ref: "23:1", topic: "나는 선한 목자라", topic_en: "I am the good Shepherd", fulfilled: "요10:11", fulfilled_en: "John 10:11" },
      { ref: "24:2", topic: "그분의 승천에 대한 예시", topic_en: "Foreshadowing of His ascension", fulfilled: "행1:11, 빌2:9", fulfilled_en: "Acts 1:11, Phil 2:9" },
      { ref: "30:3", topic: "그분의 부활하심", topic_en: "His resurrection", fulfilled: "행2:32", fulfilled_en: "Acts 2:32" },
      { ref: "31:5", topic: "나의 영혼을 주님의 손에 맡기나이다", topic_en: "Into Your hands I commit My spirit", fulfilled: "눅23:46", fulfilled_en: "Luke 23:46" },
      { ref: "31:11", topic: "그분을 아는 자들로부터 멸시받음", topic_en: "Scorned by those who knew Him", fulfilled: "막14:50", fulfilled_en: "Mark 14:50" },
      { ref: "31:13", topic: "그분을 죽이자는 모략들", topic_en: "Plots to kill Him", fulfilled: "요11:53", fulfilled_en: "John 11:53" },
      { ref: "31:14-15", topic: "하나님께서 건져주실 것을 믿으심", topic_en: "Trusting God to deliver Him", fulfilled: "마27:43", fulfilled_en: "Matt 27:43" },
      { ref: "34:20", topic: "그분의 뼈가 꺽이지 아니하심", topic_en: "None of His bones broken", fulfilled: "요19:31-36", fulfilled_en: "John 19:31-36" },
      { ref: "35:11", topic: "거짓 증인들이 그분을 대적함", topic_en: "False witnesses rise against Him", fulfilled: "마26:59", fulfilled_en: "Matt 26:59" },
      { ref: "35:19", topic: "애매히 미움받으심", topic_en: "Hated without cause", fulfilled: "요15:25", fulfilled_en: "John 15:25" },
      { ref: "38:11", topic: "그분의 친구들도 돌아섬", topic_en: "Even His friends turn away", fulfilled: "눅23:49", fulfilled_en: "Luke 23:49" },
      { ref: "40:2-5", topic: "그분의 부활하심의 즐거움", topic_en: "The joy of His resurrection", fulfilled: "요20:20", fulfilled_en: "John 20:20" },
      { ref: "40:6-8", topic: "아버지의 뜻을 따르심", topic_en: "Following the Father's will", fulfilled: "요4:34", fulfilled_en: "John 4:34" },
      { ref: "40:9", topic: "이스라엘에게 그분의 공의를 선포하심", topic_en: "Proclaiming His righteousness to Israel", fulfilled: "마4:17", fulfilled_en: "Matt 4:17" },
      { ref: "40:14", topic: "그분을 찾는 자들이 동산까지 옴", topic_en: "Those seeking Him come to the garden", fulfilled: "요18:2-3", fulfilled_en: "John 18:2-3" },
      { ref: "41:9", topic: "그분의 떡을 받은 친구가 배반함", topic_en: "A friend who ate His bread betrays Him", fulfilled: "요13:18", fulfilled_en: "John 13:18" },
      { ref: "45:2", topic: "그분의 입술에서 나오는 은혜의 말씀들", topic_en: "Words of grace from His lips", fulfilled: "눅4:22", fulfilled_en: "Luke 4:22" },
      { ref: "45:6", topic: "그분의 한 이름 하나님 혹은 엘로힘", topic_en: "His name: God or Elohim", fulfilled: "히1:8", fulfilled_en: "Heb 1:8" },
      { ref: "45:7", topic: "한 특별하신 성령님의 기름부으심", topic_en: "A special anointing of the Holy Spirit", fulfilled: "마3:16, 히1:9", fulfilled_en: "Matt 3:16, Heb 1:9" },
      { ref: "45:7-8", topic: "그리스도라 불리우심(메시아 혹은 기름부음을 받으신 분)", topic_en: "Called Christ (Messiah, the Anointed One)", fulfilled: "눅2:11", fulfilled_en: "Luke 2:11" },
      { ref: "55:12-14", topic: "타인이 아닌 친구로부터 버림받으심", topic_en: "Betrayed not by an enemy but a friend", fulfilled: "요13:18", fulfilled_en: "John 13:18" },
      { ref: "55:15", topic: "배반자의 죽음", topic_en: "Death of the betrayer", fulfilled: "마27:3-5, 행1:16-19", fulfilled_en: "Matt 27:3-5, Acts 1:16-19" },
      { ref: "68:18", topic: "사람들에게 주신 은사들", topic_en: "Gifts given to men", fulfilled: "엡4:11-16", fulfilled_en: "Eph 4:11-16" },
      { ref: "68:18", topic: "주님의 승천하심", topic_en: "The Lord's ascension", fulfilled: "눅24:51", fulfilled_en: "Luke 24:51" },
      { ref: "69:4", topic: "무고히 미움 받으심", topic_en: "Hated without cause", fulfilled: "요15:25", fulfilled_en: "John 15:25" },
      { ref: "69:8", topic: "형제들에게 외면당하심", topic_en: "Estranged from His brothers", fulfilled: "눅8:20-21", fulfilled_en: "Luke 8:20-21" },
      { ref: "69:9", topic: "주님의 집에 대한 열심", topic_en: "Zeal for the Lord's house", fulfilled: "요2:17", fulfilled_en: "John 2:17" },
      { ref: "69:14-20", topic: "메시야의 영혼의 곤고하심", topic_en: "The Messiah's anguish of soul", fulfilled: "마26:36-45", fulfilled_en: "Matt 26:36-45" },
      { ref: "69:20", topic: "나의 혼의 곤고함이 넘침", topic_en: "My heart is broken within me", fulfilled: "마26:38", fulfilled_en: "Matt 26:38" },
      { ref: "69:21", topic: "식초를 마시우게 줌", topic_en: "Given vinegar to drink", fulfilled: "마27:34", fulfilled_en: "Matt 27:34" },
      { ref: "69:26", topic: "하나님께서 구원자를 고난에 내어주심", topic_en: "God gives the Savior over to suffering", fulfilled: "요17:4, 18:11", fulfilled_en: "John 17:4, 18:11" },
      { ref: "72:10-11", topic: "지혜자들이 그분을 방문함", topic_en: "Wise men visit Him", fulfilled: "마2:1-11", fulfilled_en: "Matt 2:1-11" },
      { ref: "72:16", topic: "그분 안에 넘치는 열매들", topic_en: "Abundant fruit in Him", fulfilled: "요12:24", fulfilled_en: "John 12:24" },
      { ref: "72:17", topic: "그분의 이름을 믿는 자들의 권세", topic_en: "Power for those who believe in His name", fulfilled: "요1:12-13", fulfilled_en: "John 1:12-13" },
      { ref: "72:17", topic: "그분을 통해 모든 민족이 복을 받음", topic_en: "All nations blessed through Him", fulfilled: "행2:11, 12, 41", fulfilled_en: "Acts 2:11, 12, 41" },
      { ref: "78:1-2", topic: "그분께서 비유로 가르치심", topic_en: "He teaches in parables", fulfilled: "마13:34-35", fulfilled_en: "Matt 13:34-35" },
      { ref: "78:2", topic: "그분께서 하나님의 지혜와 권위로 말씀하심", topic_en: "He speaks with God's wisdom and authority", fulfilled: "마7:29", fulfilled_en: "Matt 7:29" },
      { ref: "88:8", topic: "그분의 아는 자를 멀리 있게 하심", topic_en: "His acquaintances kept at a distance", fulfilled: "눅23:49", fulfilled_en: "Luke 23:49" },
      { ref: "89:27", topic: "임마누엘 하나님. 왕들 중에 가장 크신 분", topic_en: "Immanuel God — highest of the kings", fulfilled: "눅1:32-33", fulfilled_en: "Luke 1:32-33" },
      { ref: "89:35-37", topic: "다윗의 씨, 보라, 왕권이 영원하심", topic_en: "Seed of David — His throne endures forever", fulfilled: "눅1:32-33", fulfilled_en: "Luke 1:32-33" },
      { ref: "89:35-37", topic: "그분의 열매가 넘침", topic_en: "His fruit endures", fulfilled: "계1:5", fulfilled_en: "Rev 1:5" },
      { ref: "90:2", topic: "영원으로부터 오신 주님", topic_en: "The Lord who is from eternity", fulfilled: "요1:1", fulfilled_en: "John 1:1" },
      { ref: "91:11-12", topic: "위험에서 승리하신 그리스도", topic_en: "Christ victorious over danger", fulfilled: "눅4:10-11", fulfilled_en: "Luke 4:10-11" },
      { ref: "97:9", topic: "가장 높으신 그분", topic_en: "Most High above all", fulfilled: "행1:11, 엡1:20", fulfilled_en: "Acts 1:11, Eph 1:20" },
      { ref: "100:5", topic: "그분의 거룩하시고 선하심", topic_en: "His holiness and goodness", fulfilled: "마19:16-17", fulfilled_en: "Matt 19:16-17" },
      { ref: "102:1-11", topic: "그분의 고난과 갈보리의 멸시받으심", topic_en: "His suffering and reproach at Calvary", fulfilled: "요21:16-30", fulfilled_en: "John 21:16-30" },
      { ref: "102:25-27", topic: "창조주의 아들은 메시아이심", topic_en: "The Creator's Son is the Messiah", fulfilled: "히1:10-12", fulfilled_en: "Heb 1:10-12" },
      { ref: "109:25", topic: "조롱을 받으심", topic_en: "Mocked and scorned", fulfilled: "마27:39", fulfilled_en: "Matt 27:39" },
      { ref: "110:1", topic: "다윗의 아들", topic_en: "Son of David", fulfilled: "마1:1, 마22:43", fulfilled_en: "Matt 1:1, Matt 22:43" },
      { ref: "110:1", topic: "하나님 우편에 앉으심", topic_en: "Seated at the right hand of God", fulfilled: "마16:19", fulfilled_en: "Matt 16:19" },
      { ref: "110:1", topic: "다윗의 아들이 주님이라 불리우심", topic_en: "David's Son called Lord", fulfilled: "마22:44-45", fulfilled_en: "Matt 22:44-45" },
      { ref: "110:4", topic: "멜기세덱의 반열의 대제사장", topic_en: "High Priest in the order of Melchizedek", fulfilled: "히6:20", fulfilled_en: "Heb 6:20" },
      { ref: "112:4", topic: "은혜와 긍휼이 많으심", topic_en: "Full of grace and compassion", fulfilled: "마9:36", fulfilled_en: "Matt 9:36" },
      { ref: "118:17-18", topic: "메시아의 부활을 예언하심", topic_en: "Prophecy of the Messiah's resurrection", fulfilled: "눅24:5-7, 고전15:20", fulfilled_en: "Luke 24:5-7, 1 Cor 15:20" },
      { ref: "118:22-23", topic: "건축자들의 버린 돌이 모퉁이의 머릿돌이 되심", topic_en: "The stone the builders rejected becomes the cornerstone", fulfilled: "마21:42-43", fulfilled_en: "Matt 21:42-43" },
      { ref: "118:26a", topic: "이스라엘을 복주심", topic_en: "Blessing Israel", fulfilled: "마21:9", fulfilled_en: "Matt 21:9" },
      { ref: "118:26b", topic: "하나님의 집에 서신 주님", topic_en: "The Lord standing in the house of God", fulfilled: "마21:12-15", fulfilled_en: "Matt 21:12-15" },
      { ref: "132:11", topic: "다윗의 씨(그 몸의 열매)", topic_en: "Seed of David (fruit of his body)", fulfilled: "눅1:32", fulfilled_en: "Luke 1:32" },
      { ref: "138:1-6", topic: "왕들이 다윗의 씨를 영접함", topic_en: "Kings receive the seed of David", fulfilled: "마2:2-6", fulfilled_en: "Matt 2:2-6" },
      { ref: "147:3-6", topic: "그리스도의 목회와 자유", topic_en: "Christ's ministry and freedom", fulfilled: "눅4:18", fulfilled_en: "Luke 4:18" },
    ],
  },
  {
    title: "아가서",
    title_en: "Song of Solomon",
    rows: [
      { ref: "5:16", topic: "그분의 교회를 사랑하심", topic_en: "His love for the church", fulfilled: "요1:17", fulfilled_en: "John 1:17" },
    ],
  },
  {
    title: "7. 이사야 — 그분께서 찔림은 나의 허물을 인함이요",
    title_en: "7. Isaiah — He Was Pierced for Our Transgressions",
    rows: [
      { ref: "6:1", topic: "이사야가 본 그분의 영광", topic_en: "Isaiah saw His glory", fulfilled: "요12:40-41", fulfilled_en: "John 12:40-41" },
      { ref: "6:9-10", topic: "깨닫지 못하는 귀들", topic_en: "Ears that cannot understand", fulfilled: "마13:13-15", fulfilled_en: "Matt 13:13-15" },
      { ref: "6:9-12", topic: "그리스도와 그분의 말씀들을 알지못함", topic_en: "Not knowing Christ and His words", fulfilled: "행28:23-29", fulfilled_en: "Acts 28:23-29" },
      { ref: "7:14", topic: "한 처녀가 아들을 낳을 것이요", topic_en: "A virgin shall bear a Son", fulfilled: "눅1:35", fulfilled_en: "Luke 1:35" },
      { ref: "7:14", topic: "임마누엘 — 하나님께서 우리와 함께 하심", topic_en: "Immanuel — God with us", fulfilled: "마1:18-23", fulfilled_en: "Matt 1:18-23" },
      { ref: "8:8", topic: "임마누엘이라 불리우심", topic_en: "Called Immanuel", fulfilled: "마28:20", fulfilled_en: "Matt 28:20" },
      { ref: "8:14", topic: "산돌을 세우시는 반석", topic_en: "The Rock and a stone of stumbling", fulfilled: "벧전2:8", fulfilled_en: "1 Pet 2:8" },
      { ref: "9:1-2", topic: "갈릴리에서의 그분의 사역", topic_en: "His ministry in Galilee", fulfilled: "마4:12-17", fulfilled_en: "Matt 4:12-17" },
      { ref: "9:6", topic: "한 아이로 태어나심", topic_en: "Born as a child", fulfilled: "눅1:31", fulfilled_en: "Luke 1:31" },
      { ref: "9:6", topic: "하나님께서 아들로 오심", topic_en: "God coming as a Son", fulfilled: "눅1:32 요1:14 딤전3:16", fulfilled_en: "Luke 1:32, John 1:14, 1 Tim 3:16" },
      { ref: "9:6", topic: "하나님 아들의 능력", topic_en: "The power of the Son of God", fulfilled: "롬1:3-4", fulfilled_en: "Rom 1:3-4" },
      { ref: "9:6", topic: "오묘하신 말씀", topic_en: "Wonderful counselor", fulfilled: "눅4:22", fulfilled_en: "Luke 4:22" },
      { ref: "9:6", topic: "기묘자라, 모사(謀士)라", topic_en: "Wonderful, Counselor", fulfilled: "마13:54", fulfilled_en: "Matt 13:54" },
      { ref: "9:6", topic: "전능하신 하나님", topic_en: "Mighty God", fulfilled: "마11:20", fulfilled_en: "Matt 11:20" },
      { ref: "9:6", topic: "영존하신 아버지", topic_en: "Everlasting Father", fulfilled: "요8:58", fulfilled_en: "John 8:58" },
      { ref: "9:6", topic: "평강의 왕이시라", topic_en: "Prince of Peace", fulfilled: "요16:33", fulfilled_en: "John 16:33" },
      { ref: "9:7", topic: "영원하신 왕국", topic_en: "His eternal kingdom", fulfilled: "눅1:32-33", fulfilled_en: "Luke 1:32-33" },
      { ref: "9:7", topic: "그분의 공의로우심", topic_en: "His righteousness", fulfilled: "요5:30", fulfilled_en: "John 5:30" },
      { ref: "9:7", topic: "끝이 없으신 그분의 나라, 평화, 보좌", topic_en: "His endless kingdom, peace, and throne", fulfilled: "눅1:32-33", fulfilled_en: "Luke 1:32-33" },
      { ref: "11:1", topic: "나사렛 사람이라 불리우리라", topic_en: "Called a Nazarene", fulfilled: "마2:23", fulfilled_en: "Matt 2:23" },
      { ref: "11:1", topic: "이새의 가지, 이새의 아들", topic_en: "Branch and Son of Jesse", fulfilled: "눅3:23-33", fulfilled_en: "Luke 3:23-33" },
      { ref: "11:2", topic: "성령님의 기름부으심", topic_en: "Anointing of the Holy Spirit", fulfilled: "마3:16-17", fulfilled_en: "Matt 3:16-17" },
      { ref: "11:2", topic: "그분의 지혜와 지각능력", topic_en: "His wisdom and understanding", fulfilled: "요4:4-26", fulfilled_en: "John 4:4-26" },
      { ref: "11:4", topic: "그분의 진리와 공의로우심", topic_en: "His truth and righteousness", fulfilled: "요14:6", fulfilled_en: "John 14:6" },
      { ref: "11:10", topic: "열방이 그분께로 오실것이요", topic_en: "The nations will come to Him", fulfilled: "요12:18-21", fulfilled_en: "John 12:18-21" },
      { ref: "12:2", topic: "예수님은 구원이라고 불리우심", topic_en: "Jesus is called Salvation", fulfilled: "마1:21", fulfilled_en: "Matt 1:21" },
      { ref: "25:8", topic: "부활하심으로 사망을 폐하심", topic_en: "Death abolished through resurrection", fulfilled: "고전15:54", fulfilled_en: "1 Cor 15:54" },
      { ref: "26:19", topic: "부활시키시는 그분의 능력", topic_en: "His power to raise the dead", fulfilled: "요11:43-44", fulfilled_en: "John 11:43-44" },
      { ref: "28:16", topic: "메시야는 귀하신 기초돌이 되심", topic_en: "The Messiah is a precious cornerstone", fulfilled: "행4:11-12", fulfilled_en: "Acts 4:11-12" },
      { ref: "29:13", topic: "그분의 말씀을 백성이 순종치 않음", topic_en: "The people do not obey His word", fulfilled: "마15:7-9", fulfilled_en: "Matt 15:7-9" },
      { ref: "29:14", topic: "지혜로우시고 오묘하신 말씀", topic_en: "Wise and wonderful words", fulfilled: "고전1:18-31", fulfilled_en: "1 Cor 1:18-31" },
      { ref: "32:2", topic: "광풍과 폭풍으로부터 피난처되시는 분", topic_en: "A shelter from the storm and wind", fulfilled: "마23:37", fulfilled_en: "Matt 23:37" },
      { ref: "35:4", topic: "그분께서 너를 구원하러 오시리라", topic_en: "He will come to save you", fulfilled: "마1:21", fulfilled_en: "Matt 1:21" },
      { ref: "35:5", topic: "깨끗하게 하시는 사역", topic_en: "His healing ministry", fulfilled: "마11:4-6", fulfilled_en: "Matt 11:4-6" },
      { ref: "40:3-4", topic: "외치는 자를 보내심", topic_en: "A voice crying in the wilderness sent before Him", fulfilled: "요1:23", fulfilled_en: "John 1:23" },
      { ref: "40:9", topic: "너희 하나님을 보라", topic_en: "Behold your God", fulfilled: "요1:36, 19:14", fulfilled_en: "John 1:36, 19:14" },
      { ref: "40:11", topic: "생명의 꼴을 먹이시는 목자", topic_en: "A Shepherd feeding the flock of life", fulfilled: "요10:10-18", fulfilled_en: "John 10:10-18" },
      { ref: "42:1-4", topic: "하나님의 기뻐하시는 종", topic_en: "God's beloved Servant", fulfilled: "마12:18-21", fulfilled_en: "Matt 12:18-21" },
      { ref: "42:2", topic: "그분은 외치지 아니하며 높히지 아니하시며", topic_en: "He does not cry out or lift up His voice", fulfilled: "마11:28-30", fulfilled_en: "Matt 11:28-30" },
      { ref: "42:3", topic: "상한 갈대와 꺼져가는 심지를 끄지 아니하심", topic_en: "Not breaking a bruised reed or quenching a smoldering wick", fulfilled: "요4", fulfilled_en: "John 4" },
      { ref: "42:4", topic: "모든 민족들이 그분의 가르침을 배움", topic_en: "All nations learn from His teaching", fulfilled: "요12:20-26", fulfilled_en: "John 12:20-26" },
      { ref: "42:6", topic: "이방인의 빛(구세주)", topic_en: "A light to the Gentiles (Savior)", fulfilled: "눅2:32", fulfilled_en: "Luke 2:32" },
      { ref: "42:1-6", topic: "그분은 모든 세상과 함께 하심", topic_en: "He is with all the world", fulfilled: "마28:19-20", fulfilled_en: "Matt 28:19-20" },
      { ref: "42:7", topic: "맹인의 눈을 뜨게 하심", topic_en: "Opening the eyes of the blind", fulfilled: "요9:25-38", fulfilled_en: "John 9:25-38" },
      { ref: "43:11", topic: "그분은 오직 단 한분이신 구세주이심", topic_en: "He alone is Savior", fulfilled: "행4:12", fulfilled_en: "Acts 4:12" },
      { ref: "44:3", topic: "그분께서 하나님의 성령님을 보내심", topic_en: "He sends the Spirit of God", fulfilled: "요16:7, 13", fulfilled_en: "John 16:7, 13" },
      { ref: "45:23", topic: "그분의 공의로우신 심판", topic_en: "His righteous judgment", fulfilled: "요5:22, 롬14:11", fulfilled_en: "John 5:22, Rom 14:11" },
      { ref: "48:12", topic: "처음과 끝이 되시는 분", topic_en: "The First and the Last", fulfilled: "요1:30 계1:8, 17", fulfilled_en: "John 1:30, Rev 1:8, 17" },
      { ref: "48:17", topic: "그분께서 가르치심", topic_en: "He teaches", fulfilled: "요3:2", fulfilled_en: "John 3:2" },
      { ref: "49:1", topic: "복중에서부터 불러내심", topic_en: "Called from the womb", fulfilled: "마1:18", fulfilled_en: "Matt 1:18" },
      { ref: "49:5", topic: "복중에서부터 종으로 부르심", topic_en: "Called as servant from the womb", fulfilled: "눅1:31, 빌2:7", fulfilled_en: "Luke 1:31, Phil 2:7" },
      { ref: "49:6", topic: "그분은 이스라엘의 구원주이시다", topic_en: "He is the Savior of Israel", fulfilled: "눅2:29-32", fulfilled_en: "Luke 2:29-32" },
      { ref: "49:6", topic: "그분은 열방의 빛이심", topic_en: "He is a light to the nations", fulfilled: "행13:47", fulfilled_en: "Acts 13:47" },
      { ref: "49:6", topic: "땅끝까지 구원을 베푸심", topic_en: "Salvation to the ends of the earth", fulfilled: "행15:3-18", fulfilled_en: "Acts 15:3-18" },
      { ref: "49:7", topic: "민족으로부터 경멸당하심", topic_en: "Despised by the nation", fulfilled: "요8:48-49", fulfilled_en: "John 8:48-49" },
      { ref: "50:3", topic: "하늘을 흑암과 굵은 베로 덮히심", topic_en: "The sky covered with darkness and sackcloth", fulfilled: "눅23:44-45", fulfilled_en: "Luke 23:44-45" },
      { ref: "50:4", topic: "곤고한 자를 쉬게하심", topic_en: "Giving rest to the weary", fulfilled: "마11:28-29", fulfilled_en: "Matt 11:28-29" },
      { ref: "50:5", topic: "반역하지 아니하시는 종", topic_en: "A servant who does not rebel", fulfilled: "마26:39", fulfilled_en: "Matt 26:39" },
      { ref: "50:6A", topic: "나를 때리는 자에게 등을 돌려주며", topic_en: "Giving His back to those who strike Him", fulfilled: "마27:26", fulfilled_en: "Matt 27:26" },
      { ref: "50:6B", topic: "그분을 때리는 자에게 뺨을 맡기며", topic_en: "Offering His cheek to those who strike Him", fulfilled: "마26:67", fulfilled_en: "Matt 26:67" },
      { ref: "50:6C", topic: "그분께서 침뱉음을 당하시고", topic_en: "He is spat upon", fulfilled: "마27:30", fulfilled_en: "Matt 27:30" },
      { ref: "52:7", topic: "평화와 좋은 소식을 가져오시는 분", topic_en: "One who brings peace and good news", fulfilled: "눅4:14-15", fulfilled_en: "Luke 4:14-15" },
      { ref: "52:13", topic: "받들어 높임을 받으신 종", topic_en: "The Servant raised and exalted", fulfilled: "행1:8-11 엡1:19-22", fulfilled_en: "Acts 1:8-11, Eph 1:19-22" },
      { ref: "52:13", topic: "보라 나의 종을...", topic_en: "Behold My Servant...", fulfilled: "마17:5 빌2:5-8", fulfilled_en: "Matt 17:5, Phil 2:5-8" },
      { ref: "52:14", topic: "상처받은 종", topic_en: "The marred Servant", fulfilled: "눅18:31-34, 마26:67-68", fulfilled_en: "Luke 18:31-34, Matt 26:67-68" },
      { ref: "52:15", topic: "열방이 놀라는 종의 말씀 선포", topic_en: "Proclamation that startles the nations", fulfilled: "롬15:18-21", fulfilled_en: "Rom 15:18-21" },
      { ref: "52:15", topic: "그분의 보혈로 모든 속죄가 이루어짐", topic_en: "All atonement accomplished through His blood", fulfilled: "계1:5", fulfilled_en: "Rev 1:5" },
      { ref: "53:1", topic: "그분의 백성들이 그분을 믿지 아니함", topic_en: "His own people do not believe in Him", fulfilled: "요12:37-38", fulfilled_en: "John 12:37-38" },
      { ref: "53:2A", topic: "우리의 보기에 아름다움이 없으신 분", topic_en: "No beauty or majesty to attract us to Him", fulfilled: "눅2:7", fulfilled_en: "Luke 2:7" },
      { ref: "53:2B", topic: "사람과 같이 낮추신 분", topic_en: "Humbled like a man", fulfilled: "빌2:7-8", fulfilled_en: "Phil 2:7-8" },
      { ref: "53:3A", topic: "경멸을 받으심", topic_en: "Despised", fulfilled: "눅4:28-29", fulfilled_en: "Luke 4:28-29" },
      { ref: "53:3B", topic: "거절당하신 분", topic_en: "Rejected", fulfilled: "마27:21-23", fulfilled_en: "Matt 27:21-23" },
      { ref: "53:3C", topic: "큰 통곡으로 우시는 분", topic_en: "A man of sorrows, weeping deeply", fulfilled: "눅19:41-42", fulfilled_en: "Luke 19:41-42" },
      { ref: "53:3D", topic: "함께 한 자들도 그분을 버림", topic_en: "Even those with Him forsook Him", fulfilled: "막14:50-52", fulfilled_en: "Mark 14:50-52" },
      { ref: "53:4A", topic: "그분은 질고를 치료하심", topic_en: "He heals diseases", fulfilled: "눅6:17-19", fulfilled_en: "Luke 6:17-19" },
      { ref: "53:4B", topic: "그분은 세상의 죄들을 짊어지심", topic_en: "He bore the sins of the world", fulfilled: "벧전2:24", fulfilled_en: "1 Pet 2:24" },
      { ref: "53:4C", topic: "하나님으로부터 끊어짐을 당하심", topic_en: "Cut off from God", fulfilled: "마27:41-43", fulfilled_en: "Matt 27:41-43" },
      { ref: "53:5A", topic: "모든 형벌을 담당하심", topic_en: "Taking all punishment upon Himself", fulfilled: "눅23:33", fulfilled_en: "Luke 23:33" },
      { ref: "53:5B", topic: "사람과 하나님의 평화의 중보자", topic_en: "Mediator of peace between God and man", fulfilled: "골1:20", fulfilled_en: "Col 1:20" },
      { ref: "53:5C", topic: "그분의 등이 채찍에 찢기심", topic_en: "His back torn by the lash", fulfilled: "마27:26", fulfilled_en: "Matt 27:26" },
      { ref: "53:6A", topic: "그분께서 모든 인류의 죄를 짊어지심", topic_en: "He bore the sins of all humanity", fulfilled: "갈1:4", fulfilled_en: "Gal 1:4" },
      { ref: "53:6B", topic: "하나님의 뜻은 그분께서 세상 죄를 담당하시는 것", topic_en: "It is God's will that He bear the sins of the world", fulfilled: "요일 4:10", fulfilled_en: "1 John 4:10" },
      { ref: "53:7A", topic: "모욕과 괴로움을 받으심", topic_en: "Oppressed and afflicted", fulfilled: "마27:27-31", fulfilled_en: "Matt 27:27-31" },
      { ref: "53:7B", topic: "그분의 고소자들 앞에서 입을 다무심", topic_en: "Silent before His accusers", fulfilled: "마27:12-14", fulfilled_en: "Matt 27:12-14" },
      { ref: "53:7C", topic: "하나님의 어린 양(희생예물)", topic_en: "The Lamb of God (sacrifice)", fulfilled: "요1:29", fulfilled_en: "John 1:29" },
      { ref: "53:8A", topic: "체포되시고 심문 당하심", topic_en: "Arrested and interrogated", fulfilled: "마26:47, 27:31", fulfilled_en: "Matt 26:47, 27:31" },
      { ref: "53:8B", topic: "그분께서 재판을 받으심", topic_en: "He is put on trial", fulfilled: "요18:13-22", fulfilled_en: "John 18:13-22" },
      { ref: "53:8C", topic: "그분께서 죽임을 당하심", topic_en: "He is put to death", fulfilled: "마27:35", fulfilled_en: "Matt 27:35" },
      { ref: "53:8D", topic: "세상의 죄들을 담당하신 죽으심", topic_en: "His death bearing the sins of the world", fulfilled: "요일2:2", fulfilled_en: "1 John 2:2" },
      { ref: "53:9A", topic: "부자의 무덤에 묻히심", topic_en: "Buried in a rich man's tomb", fulfilled: "마27:57", fulfilled_en: "Matt 27:57" },
      { ref: "53:9B", topic: "죄 없으시며 폭력을 행하시지 않으심", topic_en: "Without sin, without violence", fulfilled: "막15:3", fulfilled_en: "Mark 15:3" },
      { ref: "53:9C", topic: "그분의 입술에는 궤사가 없으심", topic_en: "No deceit in His mouth", fulfilled: "요18:38", fulfilled_en: "John 18:38" },
      { ref: "53:10A", topic: "그분께서 세상을 위해 죽으심은 하나님의 뜻", topic_en: "It is God's will that He die for the world", fulfilled: "요18:11", fulfilled_en: "John 18:11" },
      { ref: "53:10B", topic: "죄를 위한 단 한 분의 희생예물", topic_en: "The one and only sacrifice for sin", fulfilled: "마20:28", fulfilled_en: "Matt 20:28" },
      { ref: "53:10C", topic: "부활하셔서 영원히 살아계심", topic_en: "Resurrected and living forever", fulfilled: "막16:16", fulfilled_en: "Mark 16:16" },
      { ref: "53:10D", topic: "그분의 열매는 풍성하심", topic_en: "His fruit is abundant", fulfilled: "요17:1-5", fulfilled_en: "John 17:1-5" },
      { ref: "53:11A", topic: "하나님은 그분의 예물과 고통받으심을 만족하셨음", topic_en: "God is satisfied with His offering and suffering", fulfilled: "요12:27", fulfilled_en: "John 12:27" },
      { ref: "53:11B", topic: "하나님의 종", topic_en: "God's Servant", fulfilled: "롬5:18-19", fulfilled_en: "Rom 5:18-19" },
      { ref: "53:11C", topic: "그분께서 하나님 앞에서 사람을 의롭게 하심", topic_en: "He justifies man before God", fulfilled: "롬5:8-9", fulfilled_en: "Rom 5:8-9" },
      { ref: "53:11D", topic: "모든 인류를 위해 죄를 지고 가져가심", topic_en: "He bears and removes the sin of all humanity", fulfilled: "히9:28", fulfilled_en: "Heb 9:28" },
      { ref: "53:12A", topic: "그분의 희생으로 하나님께서 높혀 주심", topic_en: "God exalts Him because of His sacrifice", fulfilled: "마28:18", fulfilled_en: "Matt 28:18" },
      { ref: "53:12B", topic: "그분께서 인류를 구원하시기 위해 생명을 내어주심", topic_en: "He gives His life to save humanity", fulfilled: "눅23:46", fulfilled_en: "Luke 23:46" },
      { ref: "53:12C", topic: "악인들과 함께 처형 받으심", topic_en: "Executed among criminals", fulfilled: "눅23:32", fulfilled_en: "Luke 23:32" },
      { ref: "53:12D", topic: "모든 인류를 위해 죄를 지고 가심", topic_en: "He carries the sin of all humanity", fulfilled: "고후5:21", fulfilled_en: "2 Cor 5:21" },
      { ref: "53:12E", topic: "하나님과 사람의 중보자 되심", topic_en: "He becomes mediator between God and man", fulfilled: "눅23:34", fulfilled_en: "Luke 23:34" },
      { ref: "55:3", topic: "하나님에 의해 부활하심", topic_en: "Raised by God", fulfilled: "행13:34", fulfilled_en: "Acts 13:34" },
      { ref: "55:4", topic: "한 증인이 되심", topic_en: "Becoming a witness", fulfilled: "요18:37", fulfilled_en: "John 18:37" },
      { ref: "59:15-16A", topic: "그분은 구원하시러 오심", topic_en: "He comes to save", fulfilled: "요6:40", fulfilled_en: "John 6:40" },
      { ref: "59:15-16B", topic: "하나님과 사람 사이의 중보자", topic_en: "Intercessor between God and man", fulfilled: "마10:32", fulfilled_en: "Matt 10:32" },
      { ref: "59:20", topic: "그들의 구속자로 시온에 오심", topic_en: "Coming to Zion as their Redeemer", fulfilled: "눅2:38", fulfilled_en: "Luke 2:38" },
      { ref: "61:1-2A", topic: "그분 위에 계신 하나님의 성령님", topic_en: "The Spirit of God upon Him", fulfilled: "마3:16-17", fulfilled_en: "Matt 3:16-17" },
      { ref: "61:1-2B", topic: "그분 메시야는 좋은 소식을 전하심", topic_en: "The Messiah proclaims good news", fulfilled: "눅4:17-21", fulfilled_en: "Luke 4:17-21" },
      { ref: "61:1-2C", topic: "죄와 사망의 구속으로부터 자유케하심", topic_en: "Freedom from the bondage of sin and death", fulfilled: "요8:31-32", fulfilled_en: "John 8:31-32" },
      { ref: "61:1-2D", topic: "은혜의 시대를 선포하심", topic_en: "Proclaiming the year of God's favor", fulfilled: "요5:24", fulfilled_en: "John 5:24" },
    ],
  },
  {
    title: "8. 예레미야 — 백성을 향하신 애통",
    title_en: "8. Jeremiah — Lamentation for the People",
    rows: [
      { ref: "23:5-6A", topic: "다윗의 후손", topic_en: "Descendant of David", fulfilled: "눅3:23-31", fulfilled_en: "Luke 3:23-31" },
      { ref: "23:5-6B", topic: "메시야는 하나님이심", topic_en: "The Messiah is God", fulfilled: "요13:13", fulfilled_en: "John 13:13" },
      { ref: "23:5-6C", topic: "메시야는 참 하나님과 참 사람이 되심", topic_en: "The Messiah is fully God and fully man", fulfilled: "딤전3:16", fulfilled_en: "1 Tim 3:16" },
      { ref: "31:22", topic: "한 처녀로부터 나심", topic_en: "Born of a virgin", fulfilled: "마1:18-20", fulfilled_en: "Matt 1:18-20" },
      { ref: "31:31", topic: "메시야는 새 약속이 되심", topic_en: "The Messiah becomes the new covenant", fulfilled: "마26:28", fulfilled_en: "Matt 26:28" },
      { ref: "33:14-15", topic: "다윗의 후손", topic_en: "Descendant of David", fulfilled: "눅3:23-31", fulfilled_en: "Luke 3:23-31" },
    ],
  },
  {
    title: "에스겔",
    title_en: "Ezekiel",
    rows: [
      { ref: "17:22-24", topic: "다윗의 후손", topic_en: "Descendant of David", fulfilled: "눅3:21-23", fulfilled_en: "Luke 3:21-23" },
      { ref: "34:23-24", topic: "다윗의 후손", topic_en: "Descendant of David", fulfilled: "마1:1", fulfilled_en: "Matt 1:1" },
    ],
  },
  {
    title: "9. 다니엘 — 죄들을 종결하시다",
    title_en: "9. Daniel — He Puts an End to Sin",
    rows: [
      { ref: "7:13-14A", topic: "그분은 하늘에 오르심", topic_en: "He ascends into heaven", fulfilled: "행전1:9-11", fulfilled_en: "Acts 1:9-11" },
      { ref: "7:13-14B", topic: "최고의 높이 올려지심", topic_en: "Exalted to the highest place", fulfilled: "엡1:20-22", fulfilled_en: "Eph 1:20-22" },
      { ref: "7:13-14C", topic: "그분의 통치권은 영원하심", topic_en: "His dominion is everlasting", fulfilled: "눅1:31-33", fulfilled_en: "Luke 1:31-33" },
      { ref: "9:24A", topic: "죄를 끝내심", topic_en: "He brings sin to an end", fulfilled: "갈1:3-5", fulfilled_en: "Gal 1:3-5" },
      { ref: "9:24B", topic: "그분께서는 거룩하신 분", topic_en: "He is the Holy One", fulfilled: "눅1:35", fulfilled_en: "Luke 1:35" },
      { ref: "9:25", topic: "그분의 백성들에게 70주를 언약하심", topic_en: "The covenant of seventy weeks for His people", fulfilled: "요12:12-13", fulfilled_en: "John 12:12-13" },
      { ref: "9:26A", topic: "그분께서 죽임을 당하심", topic_en: "He is cut off", fulfilled: "마27:35", fulfilled_en: "Matt 27:35" },
      { ref: "9:26B", topic: "세상죄를 위해 죽으심", topic_en: "He dies for the sins of the world", fulfilled: "히2:9", fulfilled_en: "Heb 2:9" },
      { ref: "9:26C", topic: "그분의 희생으로 유대 성전이 무용하게됨", topic_en: "His sacrifice renders the Jewish temple obsolete", fulfilled: "마27:50-51", fulfilled_en: "Matt 27:50-51" },
      { ref: "9:27", topic: "그분께서 율법에따른 제사를 폐지하심", topic_en: "He abolishes the sacrifices required by the Law", fulfilled: "히10:18", fulfilled_en: "Heb 10:18" },
      { ref: "10:5-6", topic: "가장 높으시며 영광스러우신 메시야", topic_en: "The Messiah, most high and glorious", fulfilled: "계1:13-16", fulfilled_en: "Rev 1:13-16" },
    ],
  },
  {
    title: "10. 호세아 · 요엘 · 미가 · 학개 — 베들레헴에 오신 구주",
    title_en: "10. Hosea · Joel · Micah · Haggai — The Savior Who Came to Bethlehem",
    rows: [
      { ref: "호 13:14", topic: "그분께서 사망을 물리치심", topic_en: "He defeats death", fulfilled: "고전15:55-57", fulfilled_en: "1 Cor 15:55-57" },
      { ref: "욜 2:32", topic: "모든 인류에게 구원을 선물하심", topic_en: "Salvation given as a gift to all humanity", fulfilled: "롬10:12-13", fulfilled_en: "Rom 10:12-13" },
      { ref: "미 5:2A", topic: "베들레헴에서 태어나심", topic_en: "Born in Bethlehem", fulfilled: "마2:1-2", fulfilled_en: "Matt 2:1-2" },
      { ref: "미 5:2B", topic: "하나님의 종", topic_en: "Servant of God", fulfilled: "요15:10", fulfilled_en: "John 15:10" },
      { ref: "미 5:2C", topic: "영원부터 계신 분", topic_en: "One whose origins are from eternity", fulfilled: "요8:58", fulfilled_en: "John 8:58" },
      { ref: "학 2:6-9", topic: "그분께서 헤롯 성전을 방문하심", topic_en: "He visits Herod's temple", fulfilled: "눅2:27-32", fulfilled_en: "Luke 2:27-32" },
      { ref: "학 2:23", topic: "스룹바벨의 후손", topic_en: "Descendant of Zerubbabel", fulfilled: "눅3:23-27", fulfilled_en: "Luke 3:23-27" },
    ],
  },
  {
    title: "11. 스가랴 — 겸손하신 왕의 입성",
    title_en: "11. Zechariah — The Entry of the Humble King",
    rows: [
      { ref: "3:8", topic: "하나님의 종", topic_en: "God's Servant", fulfilled: "요17:4", fulfilled_en: "John 17:4" },
      { ref: "6:12-13", topic: "제사장이시며 왕이심", topic_en: "Both Priest and King", fulfilled: "히8:1", fulfilled_en: "Heb 8:1" },
      { ref: "9:9A", topic: "예루살렘에서 즐거움으로 영접받으심", topic_en: "Received with joy in Jerusalem", fulfilled: "마21:8-10", fulfilled_en: "Matt 21:8-10" },
      { ref: "9:9B", topic: "보라 왕이 오신다", topic_en: "Behold, your King comes", fulfilled: "요12:12-13", fulfilled_en: "John 12:12-13" },
      { ref: "9:9C", topic: "메시야께서 공의로 행하심", topic_en: "The Messiah acts in righteousness", fulfilled: "요5:30", fulfilled_en: "John 5:30" },
      { ref: "9:9D", topic: "메시야께서 구원을 선물하심", topic_en: "The Messiah brings salvation as a gift", fulfilled: "눅19:10", fulfilled_en: "Luke 19:10" },
      { ref: "9:9", topic: "메시야께서 낮아지심", topic_en: "The Messiah humbles Himself", fulfilled: "마11:29", fulfilled_en: "Matt 11:29" },
      { ref: "9:9F", topic: "나귀새끼를 타시고 예루살렘에 입성하심", topic_en: "Entering Jerusalem on a donkey's colt", fulfilled: "마21:6-9", fulfilled_en: "Matt 21:6-9" },
      { ref: "10:4", topic: "모퉁이 기초돌 되시는 분", topic_en: "The cornerstone", fulfilled: "엡2:20", fulfilled_en: "Eph 2:20" },
      { ref: "11:4-6A", topic: "그분께서 오실 때 이스라엘은 불의한 지도자들이 있을것임", topic_en: "Unjust leaders in Israel when He comes", fulfilled: "마23:1-4", fulfilled_en: "Matt 23:1-4" },
      { ref: "11:4-6B", topic: "그분을 거절함으로 하나님께서도 그들을 버리심", topic_en: "God forsakes them because they reject Him", fulfilled: "눅19:41-44", fulfilled_en: "Luke 19:41-44" },
      { ref: "11:4-6C", topic: "이스라엘이 다른 왕을 기다리며 그분을 거절함", topic_en: "Israel rejects Him while waiting for another king", fulfilled: "요19:13-15", fulfilled_en: "John 19:13-15" },
      { ref: "11:7", topic: "가난한 자와 믿는 남은 자들을 섬기심", topic_en: "Serving the poor and the believing remnant", fulfilled: "마9:35-36", fulfilled_en: "Matt 9:35-36" },
      { ref: "11:8A", topic: "이스라엘의 불신이 메시야로 하여금 그들을 거절하게 하심", topic_en: "Israel's unbelief causes the Messiah to reject them", fulfilled: "마23:33", fulfilled_en: "Matt 23:33" },
      { ref: "11:8B", topic: "그분께서 모욕을 당하심", topic_en: "He is treated with contempt", fulfilled: "마27:20", fulfilled_en: "Matt 27:20" },
      { ref: "11:9", topic: "그분을 거절한 자들에게 사역을 멈추심", topic_en: "He stops ministering to those who reject Him", fulfilled: "마13:10-11", fulfilled_en: "Matt 13:10-11" },
      { ref: "11:10-11A", topic: "이스라엘이 그분을 거절함으로 하나님께서도 그들의 보호를 거두심", topic_en: "God withdraws protection because Israel rejects Him", fulfilled: "눅19:41-44", fulfilled_en: "Luke 19:41-44" },
      { ref: "11:10-11B", topic: "메시야는 곧 하나님이심", topic_en: "The Messiah is God", fulfilled: "요14:7", fulfilled_en: "John 14:7" },
      { ref: "11:12-13A", topic: "은 30량에 배반당하심", topic_en: "Betrayed for thirty pieces of silver", fulfilled: "마26:14-15", fulfilled_en: "Matt 26:14-15" },
      { ref: "11:12-13B", topic: "이스라엘로부터 거절당하심", topic_en: "Rejected by Israel", fulfilled: "마26:14-15", fulfilled_en: "Matt 26:14-15" },
      { ref: "11:12-13C", topic: "은 30이 성전 앞에 던져짐", topic_en: "Thirty pieces of silver thrown into the temple", fulfilled: "마27:3-5", fulfilled_en: "Matt 27:3-5" },
      { ref: "11:12-13D", topic: "메시야는 곧 하나님이심", topic_en: "The Messiah is God", fulfilled: "요12:45", fulfilled_en: "John 12:45" },
      { ref: "12:10A", topic: "메시야의 육체가 못박히심", topic_en: "The Messiah's body is pierced with nails", fulfilled: "요19:34-37", fulfilled_en: "John 19:34-37" },
      { ref: "12:10B", topic: "메시야는 참 하나님이시며 참 사람이심", topic_en: "The Messiah is fully God and fully man", fulfilled: "요10:30", fulfilled_en: "John 10:30" },
      { ref: "12:10C", topic: "메시야는 이스라엘에게 거절당하심", topic_en: "The Messiah is rejected by Israel", fulfilled: "요1:11", fulfilled_en: "John 1:11" },
      { ref: "13:7A", topic: "하나님의 뜻은 그분께서 인류를 위해 희생하시는 것임", topic_en: "God's will is that He sacrifice Himself for humanity", fulfilled: "요18:11", fulfilled_en: "John 18:11" },
      { ref: "13:7B", topic: "극한 폭력을 당하시고 희생하심", topic_en: "He suffers extreme violence and sacrifices Himself", fulfilled: "마27:35", fulfilled_en: "Matt 27:35" },
      { ref: "13:7C", topic: "그분은 참 하나님이시며 참 사람이심", topic_en: "He is fully God and fully man", fulfilled: "요14:9", fulfilled_en: "John 14:9" },
      { ref: "13:7D", topic: "이스라엘이 그분을 거절함으로 흩어짐", topic_en: "Israel scattered because they reject Him", fulfilled: "마26:31-56", fulfilled_en: "Matt 26:31-56" },
    ],
  },
  {
    title: "12. 말라기 — 치료하시는 광선",
    title_en: "12. Malachi — The Sun of Righteousness with Healing",
    rows: [
      { ref: "3:1A", topic: "메시야를 위한 길을 예비하는 사자", topic_en: "A messenger preparing the way for the Messiah", fulfilled: "마11:10", fulfilled_en: "Matt 11:10" },
      { ref: "3:1B", topic: "갑작스러운 성전 방문을 하심", topic_en: "Sudden visit to the temple", fulfilled: "막11:15-16", fulfilled_en: "Mark 11:15-16" },
      { ref: "3:1C", topic: "새 언약의 전파자", topic_en: "Herald of the new covenant", fulfilled: "눅4:43", fulfilled_en: "Luke 4:43" },
      { ref: "4:5", topic: "엘리야의 영이 있는 선구자", topic_en: "A forerunner with the spirit of Elijah", fulfilled: "마3:1-2", fulfilled_en: "Matt 3:1-2" },
      { ref: "4:6", topic: "선구자는 많은 사람을 의롭게하심", topic_en: "The forerunner turns many to righteousness", fulfilled: "눅1:16-17", fulfilled_en: "Luke 1:16-17" },
    ],
  },
];
